### ISSUE TITLE
public function getEmailAuthCode(): string; make it nullable

### ISSUE THREAD

**Issue by naumanafzal0313** [scheb/2fa#101]
can you make it nullable?
it is already nullable in googleauthenticator but not in email.

**Comment by scheb** [comment]
Can't do that within version 5, as it would be a BC break.

As far as I remember, the original reasoning was that `getEmailAuthCode` would only be called when `isEmailAuthEnabled` was `true`.

**Comment by scheb** [comment]
Will change in 6.x
