### ISSUE TITLE
How to get TwoFactorInterface $user object to call reSend

### ISSUE THREAD

**Issue by 6502nmos** [scheb/2fa#102]
**Bundle version**: 5.10.1
**Symfony version**: 5.2.11
**PHP version**: 7.4.20
**Using authenticators** (`enable_authenticator_manager: true`): YES 

**Description**

Just a usage question for the reSend method as documented:

Re-send Authentication Code

When you're using the default authentication code generator that is coming with the bundle, there's an easy way to re-send the email with the authentication code. Get/inject service scheb_two_factor.security.email.code_generator and call method reSend(\Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface $user).

My question is:

In a controller what is the best way to get the TwoFactorInterface object to pass to the reSend method? I am implementing a resend code button on the code entry form. The button goes to a route in my controller which calls the reSend Method and is routine correctly through access_control:

        - { path: ^/resend_code, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

I can inject the Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\Generator\CodeGeneratorInterface into the controller method for the route so as to access the reSend method but can't work out where to get the TwoFactorInterface '$user' object in the controller code to pass to the reSend method.

Many thanks

**Comment by scheb** [comment]
`TwoFactorInterface` should be implemented by your user object, so you fetch the user object :) If you're extending your controller from Symfony's base controller class, it is `$this->getUser()` (not 100% about that).

**Comment by 6502nmos** [comment]
Yes it is implemented in my user entity - so obvious - many thanks for the swift pointer.
