### ISSUE TITLE
AuthenticatorInterface not found

### ISSUE THREAD

**Issue by umpirsky** [scheb/2fa#104]
**Bundle version**: 5.11.0
**Symfony version**: 4.4.11
**PHP version**: 7.4
**Using authenticators** (`enable_authenticator_manager: true`): Not applicable to Symfony 4.4.11.

**Description**

```
ClassNotFoundException: Attempted to load interface "AuthenticatorInterface" from namespace "Symfony\Component\Security\Http\Authenticator".
```

According to composer [version  requirements](https://packagist.org/packages/scheb/2fa), Symfony 4.4.11 is supported. But there is no `Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface` defined in that version.

**To Reproduce**

Steps to reproduce the behavior: Install Symfony and bundle versions specified above

**Comment by scheb** [comment]
That's odd, there shouldn't be any reason for the bundle to do anything with that interface under Symfony 4.4. Also, [the integration tests](https://github.com/scheb/2fa/runs/3304184607?check_suite_focus=true) (which litterally run a Symfony application) do fine on Symfony 4.4.*.

Did you already try completely removing the cache folder? Maybe some leftover there.

Could you please provide a stack trace where this error is happening?

**Comment by vitaly-chess** [comment]
removed old bundle and installed new one:
```
$ php ./composer.phar remove scheb/two-factor-bundle

$ php ./composer.phar require scheb/2fa-bundle
$ php ./composer.phar require scheb/2fa-backup-code
$ php ./composer.phar require scheb/2fa-trusted-device
$ php ./composer.phar require scheb/2fa-google-authenticator
$ php ./composer.phar require scheb/2fa-qr-code
```
flushed the cache:
```
$ rm -rf /tmp/chess/api/cache; rm -rf /tmp/chess/app/cache;
```
got:
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load interface "AuthenticatorInterface" from namespace "Symfony\Component\Security\Http\Authenticator".
Did you forget a "use" statement for e.g. "Symfony\Component\Mailer\Transport\Smtp\Auth\AuthenticatorInterface" or "Symfony\Component\Security\Guard\AuthenticatorInterface"? in /www/sites/example.com/current/vendor/scheb/2fa-bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php:36
Stack trace:
#0 /www/sites/example.com/current/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(163): include()
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Scheb\\TwoFactor...')
#2 [internal function]: spl_autoload_call('Scheb\\TwoFactor...')
#3 /www/sites/example.com/current/src/Chess/CoreBundle/DependencyInjection/Compiler/InjectFeatureManagerCompilerPass.php(31): class_exists('Scheb\\TwoFactor...')
#4 /www/sites/example.com/current/src/Chess/CoreBundle/DependencyInjection/Compiler/InjectFeature in /www/sites/example.com/current/vendor/scheb/2fa-bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php on line 36
```

**Comment by vitaly-chess** [comment]
removed old bundle and installed new one:
```
$ php ./composer.phar remove scheb/two-factor-bundle

$ php ./composer.phar require scheb/2fa-bundle
$ php ./composer.phar require scheb/2fa-backup-code
$ php ./composer.phar require scheb/2fa-trusted-device
$ php ./composer.phar require scheb/2fa-google-authenticator
$ php ./composer.phar require scheb/2fa-qr-code
```
flushed the cache:
```
$ rm -rf /tmp/example/api/cache; rm -rf /tmp/example/app/cache;
```
got:
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load interface "AuthenticatorInterface" from namespace "Symfony\Component\Security\Http\Authenticator".
Did you forget a "use" statement for e.g. "Symfony\Component\Mailer\Transport\Smtp\Auth\AuthenticatorInterface" or "Symfony\Component\Security\Guard\AuthenticatorInterface"? in /www/sites/example.com/current/vendor/scheb/2fa-bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php:36
Stack trace:
#0 /www/sites/example.com/current/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(163): include()
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Scheb\\TwoFactor...')
#2 [internal function]: spl_autoload_call('Scheb\\TwoFactor...')
#3 /www/sites/example.com/current/src/Example/CoreBundle/DependencyInjection/Compiler/InjectFeatureManagerCompilerPass.php(31): class_exists('Scheb\\TwoFactor...')
#4 /www/sites/example.com/current/src/Example/CoreBundle/DependencyInjection/Compiler/InjectFeature in /www/sites/example.com/current/vendor/scheb/2fa-bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php on line 36
```

**Comment by scheb** [comment]
@vitaly-chess Are you speaking for @umpirsky or are you just having a similar problem?

**Comment by umpirsky** [comment]
We are working together on this problem. :)

**Comment by scheb** [comment]
Ok, good. Debugging two problems in the same issue is always a mess XD

Could you show me what's going on in `InjectFeatureManagerCompilerPass.php(31)` in context and what class it's trying to load `class_exists('Scheb\\TwoFactor...')` (doesn't show the full name).

**Comment by umpirsky** [comment]
Sorry, my bad, I updated issue description. https://github.com/scheb/2fa/issues/104#issuecomment-900122599 is the correct issue description.

**Comment by vitaly-chess** [comment]
> Could you show me what's going on in InjectFeatureManagerCompilerPass.php(31) in context and what class it's trying to load class_exists('Scheb\\TwoFactor...') (doesn't show the full name).

    Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator
```
        if (!class_exists($class)) {
            return false;
        }
```

**Comment by umpirsky** [comment]
```php
class_exists('Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator')
```

**Comment by umpirsky** [comment]
Well, we are trying to check if `Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator` exist, and we removed `scheb/two-factor-bundle`. So looks like we found the issue. Right @vitaly-chess?

**Comment by scheb** [comment]
Could it be that you're iterating all DIC service definitions and you're trying to load each of the classes refrenced in the service definitons?

**Comment by umpirsky** [comment]
Yes, yes, that is the case. Thanks for helping with this, sorry for the noise.

**Comment by vitaly-chess** [comment]
namespace `Scheb\TwoFactorBundle` exists in both bundles.
`Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator` belongs to bundle `scheb/2fa` (not `scheb/two-factor-bundle`).

**Comment by vitaly-chess** [comment]
New bundle (scheb/2fa) [uses](https://github.com/scheb/2fa/blob/5.x/src/bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php#L26
) `AuthenticatorInterface`:

Even Symfony 5.0 [has no](https://github.com/symfony/symfony/tree/5.0/src/Symfony/Component/Security/Http) that interface, when we got Symfony [4.4.11](https://github.com/symfony/symfony/tree/v4.4.11/src/Symfony/Component/Security/Http).

**Comment by scheb** [comment]
`AuthenticatorInterface` was introduced in Symfony 5.1 as part of the new authenticator-based security system. If you are on Symfony 4.4 or 5.0 there should be no reason to load the `Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator` class and respectively the non-existent `AuthenticatorInterface`.

**Comment by vitaly-chess** [comment]
Now I see.
`TwoFactorAuthenticator` has abstract service definition and we try to load the class when iterating all DIC service definitions.
Seems we need to skip abstract definitions, or skip vendor definitions.
Thanks for your time.

**Comment by tomazartack** [comment]
How did you guys solve this issue? I have the same problem after upgrading from version 4.x to 5.x. We are using symfony 4.4. It seems like the class  "Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator" depends on a few classes inside "Symfony\Component\Security\Http\Authenticator" namespace which is only available in Symfony 5. How do I prevent Symfony from autoloading this TwoFactorAuthenticator class? Thank you!

**Comment by tomazartack** [comment]
I solved it... was exactly the same case as mentioned above... we had an iteration over all container classes and then in the loop a class_exists call in one of the CompilerPasses. Thanks guys! :)
