### ISSUE TITLE
Whitelisted routes (accessible during two-factor authentication)

### ISSUE THREAD

**Issue by hdumazeau** [scheb/2fa#111]
**Bundle version: 5.x
Symfony version: Any
PHP version: Any
Using authenticators Any**

**Description**
In the readme is written: Whitelisted routes (accessible during two-factor authentication)
I can't find this feature in the doc.
How do I make a route accessible during the two-factor authentication ?

**Comment by scheb** [comment]
You need to configure the paths with `IS_AUTHENTICATED_ANONYMOUSLY` (or `PUBLIC_ACCESS` in newer Symfony versions) in the security `access_control` configuration.

**Comment by hdumazeau** [comment]
Thanks !
