### ISSUE TITLE
How to control user 2fa state

### ISSUE THREAD

**Issue by osavchenko** [scheb/2fa#113]
**Bundle version**: 5.13.0
**Symfony version**: 5.3
**PHP version**: 7.4
**Using authenticators** YES

**Description**

I want to force users to have 2fa and I want to control in which state the user is: 2fa is not set up, 2fa setup is in progress, 2fa setup is complete, the user is required to enter 2fa code, the user is fully logged in.

Also, I'm using a Symfony login link and could you please advise how to handle 2fa with such functionality? I know that it's more like the Symfony security component feature, but maybe you are faced with it.

Thank you in advance.

**Comment by scheb** [comment]
> I want to force users to have 2fa and I want to control in which state the user is: 2fa is not set up, 2fa setup is in progress, 2fa setup is complete, the user is required to enter 2fa code, the user is fully logged in.

If you want to force 2fa, you have make sure during account creation that the user is activating one of the available 2fa methods. The bundle itself is not forcing 2fa.

> Also, I'm using a Symfony login link and could you please advise how to handle 2fa with such functionality? I know that it's more like the Symfony security component feature, but maybe you are faced with it.

That depends on what you want. If you want 2fa when using a login link, or not. I believe per default 2fa should be required when using a login link.

**Comment by osavchenko** [comment]
Thank you for your answer!

> The bundle itself is not forcing 2fa.

It was solved by extending the `IS_AUTHENTICATED_FULLY` attribute check.

> I believe per default 2fa should be required when using a login link.

Yes, it works well with the login link feature by default. There was my own issue there.
