### ISSUE TITLE
The controller for URI "/2fa" is not callable: Controller "scheb_two_factor.form_controller:form" does neither exist as service nor as class

### ISSUE THREAD

**Issue by dirkkredler** [scheb/2fa#120]
**Bundle version**: 6.0..
**Symfony version**: 6.0.2
**PHP version**: 8.0.14
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**
After upgrading to 6.0.0 and Symfony from 5.4 to 6.0 we got at some point the above noted error.
Strange enough, `bin/console debug:container scheb_two_factor.form_controller` shows

Information for Service "scheb_two_factor.form_controller"
 ---------------- ------------------------------------------------- 
  Option           Value                                            
 ---------------- ------------------------------------------------- 
  Service ID       scheb_two_factor.form_controller                 
  Class            Scheb\TwoFactorBundle\Controller\FormController  
  Tags             -                                                
  Public           yes                                              
  Synthetic        no                                               
  Lazy             no                                               
  Shared           yes                                              
  Abstract         no                                               
  Autowired        no                                               
  Autoconfigured   no                                               
 ---------------- ------------------------------------------------- 

**Additional Context**

_config/packages/scheb_2fa.yaml_
`scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    email:
        enabled: true
        digits: 6
        sender_email: "%env(APP_MAIL)%"
        sender_name: Veranstaltung SHK-NRW
        template: security/2fa.html.twig
        mailer: App\Core\Service\MailService

    google:
        enabled: true
        template: security/2fa.html.twig`

_config/routes/scheb_2fa.yaml_
`2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /2fa_check`

_config/packages/security.yaml_
`security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # ROLE_USER
    #   a user who can log in to the application
    # ROLE_PARTICIPANT
    #   a meeting participant is a user who can participate in a meeting
    # ROLE_ORIGINATOR
    #   a meeting originator is a user which booked the meeting and can also participate in a meeting
    # ROLE_ACCOUNTANT
    #   an accountant is an admin who can fetch accounting information
    # ROLE_TRAINER
    #   a trainer executes the training and has access to an read-only view of the meeting
    # ROLE_AUTHOR
    #   an author is an admin who can setup and administer meetings
    # ROLE_AUTHOR
    #   a reviewer is an author who can review meetings from other authors before publishing
    # ROLE_ADMIN
    #   an admin who can administer the application
    role_hierarchy:
        ROLE_ADMIN:
            [
                ROLE_REVIEWER,
                ROLE_AUTHOR,
                ROLE_EDITOR,
                ROLE_ACCOUNTANT,
                ROLE_TRAINER,
                ROLE_ORIGINATOR,
                ROLE_PARTICIPANT,
                ROLE_USER,
            ]
        ROLE_REVIEWER: ROLE_EDITOR
        ROLE_AUTHOR: ROLE_EDITOR
        ROLE_EDITOR: ROLE_USER
        ROLE_ACCOUNTANT: ROLE_USER
        ROLE_TRAINER: ROLE_PARTICIPANT
        ROLE_ORIGINATOR: ROLE_PARTICIPANT
        ROLE_PARTICIPANT: ROLE_USER

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            login_throttling:
                max_attempts: 3
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
            logout:
                path: app_user_logout
                target: app_homepage

    access_control:
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS, requires_channel: https }
        - { path: ^/konto, roles: ROLE_USER, requires_channel: https }
        - { path: ^/konto/support, roles: ROLE_EDITOR, requires_channel: https }
        - { path: ^/konto/stammdaten, roles: ROLE_EDITOR, requires_channel: https }
        - { path: ^/konto/statistiken/website, roles: ROLE_EDITOR, requires_channel: https }
        - { path: ^/, roles: PUBLIC_ACCESS, requires_channel: https }`      
_

**Comment by scheb** [comment]
Under Symfony 6, the syntax to reference controllers changed. You need to use two colons, see an example here: https://github.com/scheb/2fa/blob/6.x/app/config/routes/scheb_2fa.yaml#L4

That reminds me, I need to update that in the docs and should probably add that to the upgrade note, since the bundle has previously used the old syntax.

**Comment by dirkkredler** [comment]
you are the best :+1: thank you so much and have a happy new year btw. i should have spotted this by myself, thanks for your time
