### ISSUE TITLE
QR code generator - scheb/2fa-qr-code

### ISSUE THREAD

**Issue by hracik** [scheb/2fa#123]
**Bundle version**: 6.0.1
**Symfony version**: 5.4.2
**PHP version**: 8.1
**Using authenticators** (`enable_authenticator_manager: true`): NO

**Description**

I am upgrading from 5.2 to 6.0 and used `Scheb\TwoFactorBundle\Security\TwoFactor\QrCode\QrCodeGenerator;` to generate QR code. Now it is not part of `scheb/2fa` and `composer require scheb/2fa-qr-code` fails:

```
Problem 1
    - scheb/2fa-qr-code v5.13.0 requires scheb/2fa-bundle v5.13.0 -> found scheb
/2fa-bundle[v5.13.0] but these were not loaded, likely because it conflicts with
 another require.
```

What is the solution if I want to generate QR code with current version 6.0.1?

**Comment by scheb** [comment]
That package has been discontinued, because it doesn't provide much value. See upgrade notes what to use instead: https://github.com/scheb/2fa/blob/6.x/UPGRADE.md#scheb2fa-qr-code-package

**Comment by hracik** [comment]
Thanks, you can close.
