### ISSUE TITLE
[2fa-trusted-device] cookie still valid after secret is changed

### ISSUE THREAD

**Issue by fmonts** [scheb/2fa#126]
How to reproduce:

- set a 2fa
- go to the 2fa page, check the checkbox and submit
- disable the 2fa and re-enable it with a new secret
- try to login again 
- no 2fa form is shown 

I think the user is expected to see the form again if they enabled 2fa, it doesn't matter if 10 days ago they checked "remember this device for 30 days" with an older secret.

It may also be a security vulnerability, in case a device is not trusted anymore (lost/stolen) and the user resets the 2fa to prevent it from logging again.

**Comment by fmonts** [comment]
I see old tokens can be invalidated with getTrustedTokenVersion(), I think I'll have to make it return a sort of hash of the secret. 
It would be better if it allowed strings, so one can easily do, for example:

    public function getTrustedTokenVersion(): string
    {
        return md5($this->googleAuthenticatorSecret);
    }

**Comment by scheb** [comment]
`getTrustedTokenVersion()` is there to invalidate the user's trusted devices. The business logic when you'd want to do this is up to you.

The intended solution would be to persist the version value together with the user entity and increase it whenever you need to. That would also allow the user to invalidate all trusted devices whenever they want, without changing the secret. Up to you.

The approach with the hash would also work. The hash value is de facto a number (presented in hexadecimal format), so you should be able to calculate some integer from it.
