### ISSUE TITLE
Mismatch between 2fa 6.x and Symfony 5.4 PHP version requirement

### ISSUE THREAD

**Issue by melvinkoopmans** [scheb/2fa#129]
It is said that scheb/2fa version 6.x supports Symfony 5.4, but Symfony 5.4 supports PHP >= 7.2. I just upgraded my Symfony application to 5.4 and I'm running PHP 7.4 in production. Because of that I can't make use of the 2fa bundle version 6.x though.

Is it truly necessary to force PHP 8.0? I think most people are still preparing their codebases to support 8.0. For example, we only upgrade to the next PHP version when it's the default in the latest Ubuntu LTS. PHP 8 will be released in Ubuntu 22.04 which is scheduled for April this year.

**Comment by scheb** [comment]
Short answer: Use bundle version 5.

Long answer: There is no such rule that a bundle has to support the minimum PHP version of the minimum supported Symfony version. `scheb/2fa-bundle` 6.x targets primarily Symfony 6, which has the same PHP 8.0 minimum requirement. I decided to be nice and support Symfony 5.4 as well, to make the transition between PHP and Symfony versions easier for people. Though I decided to bump the PHP version requirement to PHP 8.0 to go with an up-to-date PHP version. PHP 7.4 is outdated and was already outdated on the release of bundle version 6. It's currently in "security fixes only" mode and will be EOL by the end of this year. So I didn't see a reason to keep support for that version any longer.

**Comment by joakdatradesegur** [comment]
Hi scheb. I know it is an old issue, but I need to support both Symfony 5.4 and PHP 7.4 because we are not ready yet to use PHP 8. Please, could you consider to also support PHP 7.4 on version 6+. We need to solve Symfony 5.3+ deprecations but we could not use PHP 8 because we use other vendor libraries that are not compatible with PHP 8 yet (we are evaluating if there are needed or not). Thanks

**Comment by scheb** [comment]
Use bundle version 5 in your upgrade path. Once you've reached Symfony 5.4, you can easily upgrade to bundle version 6.
