### ISSUE TITLE
Clear code deprecations version 5.13.x

### ISSUE THREAD

**Issue by PYDeret** [scheb/2fa#130]
Hi, I was upgrading some project using 2fa bundle from Symfony 5.3 to Symfony 5.4.4, following by upgrading recipies and clearing code deprecations. But I couldn't remove all deprecations due to vendor package having them.

These are the 7 deprecations I found with Symfony's profiler : 

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/14165062/152808051-1119ee1a-b736-4897-aad1-5e8b12ccce3d.png">
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/14165062/152808129-ad178bf3-4e1f-4b4f-822d-5c22d975695c.png">

Could you remove all these deprecations from version 5.13.x (I am using 5.13.1 exactly) ?

Thanks

**Comment by scheb** [comment]
Unfortunately these can't be removed, as they're either necessary for compatibility with older supported Symfony versions or require a BC break (i.e. method signatures), which isn't possible without releasing a new major version.

In the end it's deprecation notices. They're not nice to look at, but nothing to worry about.

If you really want to get rid of them, upgrade to bundle version 6, which is implemented against the Symfony 5.4/6.x API and has all of these deprecations removed.

**Comment by PYDeret** [comment]
Thanks for the response, unfortunately, we can't use the version 6 which is requiring PHP  >= 8.0 😞 

Thanks anyway, I will close this issue.
