### ISSUE TITLE
Additional step in 2fa process

### ISSUE THREAD

**Issue by mehldau** [scheb/2fa#131]
**Bundle version**: 5.13.1
**Symfony version**: 4.4.35
**PHP version**: 7.4.24
**Using authenticators** (`enable_authenticator_manager: true`): NO

**Description**

I am currently facing a project where I have to add a 'trusted device' feature to an existing 2FA implementation.
I consider migrating to your clean implementation for farious reasons. As we don't persist the users MFA method:

**Is there any way of hooking into the process of beeing 'partially authenticated' (IS_AUTHENTICATED_2FA_IN_PROGRESS) having a page the user has to select the mfa method BEFORE beeing redirected to the authentication form to enter the code?**

Please raise my hopes und thank you for your awesome work :)

**Comment by scheb** [comment]
There is a way to define the provider to be used based on the user account [by implementing `PreferredProviderInterface`](https://symfony.com/bundles/SchebTwoFactorBundle/current/multi_authentication.html). But that would require that selection to be persisted in the user entity.

There is also a way to choose the provider to be used on the 2fa form page, using the `preferProvider` query parameter. Check out the [demo app](https://github.com/scheb/2fa/tree/5.x/app) that is part of this repository. It includes a demo to switch the 2fa form between different 2fa providers.

If you really need to have a dedicated page between login and 2fa form, the you'll likely need:

- implement and inject your own Symfony security extension to add a firewall listener
- make sure that firewall listener triggers before 2fa-bundle's listener kicks in and forces a redirect to the 2fa form
- have that firewall listener check for the "2fa in progress state" and respond with your page to select a 2fa method
- when the user selects the 2fa provider, use `TwoFactorToken::preferTwoFactorProvider(string $preferredProvider)` on the security token to make the bundle use that provider

**Comment by mehldau** [comment]
> There is a way to define the provider to be used based on the user account [by implementing `PreferredProviderInterface`](https://symfony.com/bundles/SchebTwoFactorBundle/current/multi_authentication.html). But that would require that selection to be persisted in the user entity.
> 
> There is also a way to choose the provider to be used on the 2fa form page, using the `preferProvider` query parameter. Check out the [demo app](https://github.com/scheb/2fa/tree/5.x/app) that is part of this repository. It includes a demo to switch the 2fa form between different 2fa providers.
> 
> If you really need to have a dedicated page between login and 2fa form, the you'll likely need:
> 
> * implement and inject your own Symfony security extension to add a firewall listener
> * make sure that firewall listener triggers before 2fa-bundle's listener kicks in and forces a redirect to the 2fa form
> * have that firewall listener check for the "2fa in progress state" and respond with your page to select a 2fa method
> * when the user selects the 2fa provider, use `TwoFactorToken::preferTwoFactorProvider(string $preferredProvider)` on the security token to make the bundle use that provider

Hey there,

thank you for your promt response.

To get things done I decided to implement the 'trusted device' feature manually in the first place.

But I will come back und check your proposals. In my initial test implementations I wasn't able intercept the events before your 2fa-bundle kicked in. So maybe the only solution would be your suggested way regarding an additional 'security extension'.

**Comment by scheb** [comment]
You have to go the security extension route is you want to inject something that is called after the security layer being initialized and before the 2fa access check being called. All of this is happening in firewall listeners and the only way to add a firewall listener is the security extension (or some hacky DIC manipulation, wouldn't recommend).
