### ISSUE TITLE
2fa QR code don't display form after login, access Denied when I go on /2fa

### ISSUE THREAD

**Issue by ghost** [scheb/2fa#134]
Bundle version: 6.0
Symfony version: 5.4
PHP version: 8

Hi,
when I login me on my website (localhost), the 2fa don't work, don't display the form for QR code, the user is directly connected
I dump($token) after login, response:
`object(Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken)#384 (5) { ["user":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> object(App\Entity\User)#375 (5) { ["id":"App\Entity\User":private]=> int(1) ["username":"App\Entity\User":private]=> string(4) "test" ["roles":"App\Entity\User":private]=> array(1) { [0]=> string(10) "ROLE_ADMIN" } ["password":"App\Entity\User":private]=> string(60) "$2y$13$29MlakizHLyyCtyFdh..9eDaIEQVzT4gm.IhDX1qMvTYXVlO5/G3y" ["googleAuthenticatorSecret":"App\Entity\User":private]=> NULL } ["roleNames":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> array(2) { [0]=> string(10) "ROLE_ADMIN" [1]=> string(9) "ROLE_USER" } ["authenticated":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> bool(true) ["attributes":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> array(0) { } ["firewallName":"Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken":private]=> string(4) "main" }`

```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthentificatorAuthenticator
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home, roles: ROLE_ADMIN }
```

```
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
        server_name: 2fa       # Server name used in QR code
        issuer: 2fa           # Issuer name used in QR code
        window: 1                      # How many codes before/after the current one would be accepted as valid
        template: security/2fa.html.twig
```

```
2fa_login:
         path: /2fa
         defaults:
              _controller: "scheb_two_factor.form_controller::form"

     2fa_login_check:
         path: /2fa_check
```

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route(path: '/2fa/inProgress', name: '2fa_in_progress')]
    public function accessibleDuring2fa(): Response
    {
        return new Response('This page is accessible during 2fa');
    }
}
```

```
<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\CsrfTokenBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\Util\TargetPathTrait;

class LoginFormAuthentificatorAuthenticator extends AbstractLoginFormAuthenticator
{
    use TargetPathTrait;

    public const LOGIN_ROUTE = 'app_login';

    private UrlGeneratorInterface $urlGenerator;

    public function __construct(UrlGeneratorInterface $urlGenerator)
    {
        $this->urlGenerator = $urlGenerator;
    }

    public function authenticate(Request $request): Passport
    {
        $username = $request->request->get('username', '');

        $request->getSession()->set(Security::LAST_USERNAME, $username);

        return new Passport(
            new UserBadge($username),
            new PasswordCredentials($request->request->get('password', '')),
            [
                new CsrfTokenBadge('authenticate', $request->request->get('_csrf_token')),
            ]
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $firewallName)) {
            return new RedirectResponse($targetPath);
        }

        // For example:
        return new RedirectResponse($this->urlGenerator->generate('app_home'));
        //throw new \Exception('TODO: provide a valid redirect inside '.__FILE__);
    }

    protected function getLoginUrl(Request $request): string
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}
```

**Comment by scheb** [comment]
Please follow the troubleshooting guide: https://symfony.com/bundles/SchebTwoFactorBundle/6.x/troubleshooting.html#two-factor-authentication-form-is-not-shown-after-login

**Comment by ghost** [comment]
ok I see the troubleshooting, my access_control seems good with /2fa first, my firewall also and my entity User but like I don't have TwoFactorToken after login I go on the dot 3 but where I go test this Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator::authenticate()

**Comment by scheb** [comment]
> I go on the dot 3 but where I go test this Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator::authenticate()

Sorry, but I don't understand this part of your message. Can you elaborate?

**Comment by ghost** [comment]
in [https://symfony.com/bundles/SchebTwoFactorBundle/6.x/troubleshooting.html#two-factor-authentication-form-is-not-shown-after-login](url) at the [Troubleshooting](https://symfony.com/bundles/SchebTwoFactorBundle/6.x/troubleshooting.html#troubleshooting) troubleshooting 

1. Is a TwoFactorToken present after the login? -> no -> I go on 3)

3.On login, do you reach the end (return statement) of method Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator::authenticate()?

**Comment by ghost** [comment]
my error is getActiveTwoFactorProviders return me a empty array: 
`Solution: our user doesn't have an active two-factor authentication method. Either the is*Enabled method returns false or an essential piece of data (e.g. Google Authenticator secret) is missing.`

but what is is*Enabled method (user method?) and I want just a QR code with totp not Google Authenticator secret

**Comment by ghost** [comment]
so I have a TwoFactorToken after login. When I try accessing a page that requires the user to be authenticated I access to login page (Symfony security form) but after that your bundle do not ask me the QR code. I have to go in /2fa for have QR code but anywhere I can put the code for 2fa

**Comment by scheb** [comment]
I don't really understand what you're trying to do with the QR code.

The QR code is meant to be scanned by your TOTP app (typically some app your mobile phone) in order to _set up the generation of 2fa codes_. Once you have scanned the QR code, the TOTP app will generate authentication codes, which can be entered in the 2fa form to complete the authentication process.

So the QR code is only used once when the user configures their TOTP app.

**Comment by ghost** [comment]
yes but I don't have this form after login, it's good thanks to scheb_two_factor.form_controller::form in /2fa than form display? And the /2fa is not called after  login. I have TwoFactorToken after login (dump(token)) and my access_control is good, I don't see the problem

**Comment by ghost** [comment]
and why in th /2fa route in have just the QR code but I haven't the form

**Comment by scheb** [comment]
1) So what do you see after login?

2) Once you have logged in, if you manually navigate to `/2fa`, what do you see?

**Comment by ghost** [comment]
1 => when I login me on `/login`, I redirect to `/` route with a basic controller : 
```
#[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig');
    }
```

2 => when I logged in (TwoFactorToken token) if I go on `/2fa` I have the good form currently



so the problem is => don't display form directly after login and for the `auth_code totp` where I can make QR code (it's that for display QR code `$qrCodeContent = $container->get("scheb_two_factor.security.totp_authenticator")->getQRContent($user);` ?)

**Comment by scheb** [comment]
Can you get me a dump of that `TwoFactorToken`?

What is weird, you shouldn't be able to access the `/` path in that stage, because according to your `access_control`, it requires the user to be fully authenticated (`IS_AUTHENTICATED_FULLY`), which is not the case when you have a `TwoFactorToken`.

**Comment by ghost** [comment]
`object(Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken)#403 (6) { ["authenticatedToken":"Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken":private]=> object(Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken)#383 (5) { ["user":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> object(App\Entity\User)#374 (5) { ["id":"App\Entity\User":private]=> int(1) ["username":"App\Entity\User":private]=> string(4) "test" ["roles":"App\Entity\User":private]=> array(1) { [0]=> string(10) "ROLE_ADMIN" } ["password":"App\Entity\User":private]=> string(60) "$2y$13$29MlakizHLyyCtyFdh..9eDaIEQVzT4gm.IhDX1qMvTYXVlO5/G3y" ["totpSecret":"App\Entity\User":private]=> string(52) "VLJKMIIJILMBB7XJ7NCUJD3HH44J3AC32ZOEGSKJRPIVP2MPT4IQ" } ["roleNames":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> array(2) { [0]=> string(10) "ROLE_ADMIN" [1]=> string(9) "ROLE_USER" } ["authenticated":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> bool(true) ["attributes":"Symfony\Component\Security\Core\Authentication\Token\AbstractToken":private]=> array(0) { } ["firewallName":"Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken":private]=> string(4) "main" } ["attributes":"Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken":private]=> array(0) { } ["twoFactorProviders":"Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken":private]=> array(1) { [0]=> string(4) "totp" } ["preparedProviders":"Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken":private]=> array(0) { } ["credentials":"Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken":private]=> NULL ["firewallName":"Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken":private]=> string(4) "main" }`


```
access_control:
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```


I can use `custom_authenticator: App\Security\LoginFormAuthentificatorAuthenticator` (security.yaml in firewall) for login:
```
<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Http\Authenticator\AbstractLoginFormAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\CsrfTokenBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;
use Symfony\Component\Security\Http\Authenticator\Passport\Passport;
use Symfony\Component\Security\Http\Util\TargetPathTrait;

class LoginFormAuthentificatorAuthenticator extends AbstractLoginFormAuthenticator
{
    use TargetPathTrait;

    public const LOGIN_ROUTE = 'app_login';

    private UrlGeneratorInterface $urlGenerator;

    public function __construct(UrlGeneratorInterface $urlGenerator)
    {
        $this->urlGenerator = $urlGenerator;
    }

    public function authenticate(Request $request): Passport
    {
        $username = $request->request->get('username', '');

        $request->getSession()->set(Security::LAST_USERNAME, $username);

        return new Passport(
            new UserBadge($username),
            new PasswordCredentials($request->request->get('password', '')),
            [
                new CsrfTokenBadge('authenticate', $request->request->get('_csrf_token')),
            ]
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $firewallName)) {
            return new RedirectResponse($targetPath);
        }
        // For example:
        var_dump($token);
        die;
        return new RedirectResponse($this->urlGenerator->generate('app_home'));
        //throw new \Exception('TODO: provide a valid redirect inside '.__FILE__);
    }

    protected function getLoginUrl(Request $request): string
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}
```

Or I need this [https://github.com/scheb/2fa/blob/6.x/app/config/packages/security.php](url):
```
 'form_login' => [
                'login_path' => '_security_login',
                'check_path' => '_security_login',
                'use_referer' => true,
```

**Comment by ghost** [comment]
i test again tomorrow it may be a very small mistake

**Comment by ghost** [comment]
with 2fa/email it's work perfectly but I need phone verification I go test with totp/Qrcode

**Comment by ghost** [comment]
ok I think it's work but when I arrive on `/2fa` after login (automatically) I enter the code (from my app mobile) but it's `code_invalid` message so it's possible to have QR code from this page ? with `$qrCodeContent = $container->get("scheb_two_factor.security.totp_authenticator")->getQRContent($user);` I need to make this I your controller `Scheb\TwoFactorBundle\Controller\FormController::form`

**Comment by ghost** [comment]
and I make the secret key `$secret = $container->get("scheb_two_factor.security.totp_authenticator")->generateSecret();` in my database in `$totpSecret` its ok?

**Comment by ghost** [comment]
ok Qr code I just form authenticate in app phone ([https://github.com/scheb/two-factor-bundle/issues/68](url)) but the code for 2fa updated every 30s and I see message `code_invalid`

**Comment by scheb** [comment]
I believe you're misunderstanding the concept of TOTP and what the QR code is used for. Here's a good overview, also explaining the use of the QR code: https://www.freecodecamp.org/news/how-time-based-one-time-passwords-work-and-why-you-should-use-them-in-your-app-fdd2b9ed43c3/

**Comment by ghost** [comment]
ok it's work now, the application on my phone is not good I had to take this one `FreeOTP`.
Thank you so much for your help !!
