### ISSUE TITLE
ADD the possibility to add multiple TOTP apps

### ISSUE THREAD

**Issue by tydoo** [scheb/2fa#136]
**Description**

Currently, only one totp application can be registered.
It would be interesting to add multiple totp applications like a backup codes

**Comment by scheb** [comment]
See #124 

You can do that by implementing your own 2fa provider based on the one coming with the bundle.

**Comment by tydoo** [comment]
Ok thanks.

I see that on the issue #124 , you don't want to implement it.

However, many sites today offer multiple application registrations.

So you plan to implement it?

**Comment by scheb** [comment]
No, not any time soon. It would be a BC break to the TOTP module and that could earliest be shipped with a version 7. That isn't even planned yet, as 6 just got released.

**Comment by tydoo** [comment]
OK thanks
