### ISSUE TITLE
Unable to set HTTP status code 2xx when using JSON login

### ISSUE THREAD

**Issue by Charl13** [scheb/2fa#138]
**Bundle version**: 5.13.1
**Symfony version**: 5.4.7
**PHP version**: 7.2.34
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

When using the `AuthenticationRequiredHandlerInterface::onAuthenticationRequired()` as described in the [API docs](https://github.com/scheb/2fa/blob/5.x/doc/api.rst#2-response-to-require-two-factor-authentication) it seems not possible to set the HTTP status code of the response to 2xx since this is overwritten in [`HttpKernel::handleThrowable()`](https://github.com/symfony/http-kernel/blob/5.4/HttpKernel.php#L234).

In our case when authenticating using the [`JsonLoginAuthenticator`](https://github.com/symfony/security-http/blob/5.4/Authenticator/JsonLoginAuthenticator.php) a HTTP POST request is made to our authentication endpoint and when the [`ExceptionListener::handleAccessDeniedException()`](https://github.com/scheb/2fa/blob/b89a9e3744b97323f2f2855347f0614a2b701d28/src/bundle/Security/Http/Firewall/ExceptionListener.php#L48) takes over it will always return a HTTP 500 which is not correct because login was successful.

**Comment by scheb** [comment]
I don't understand how you end up with a error 500. Error 500 indicates that you had a fatal error/exception in your Symfony application. I'd recommend you check the Symfony debug toolbar or the logs what is causing the Symfony application to error. When you run the application in `dev` mode with debug enabled, Symfony should actually display the exception trace with a lot of extra information.

How it should normally work: `ExceptionListener::handleAccessDeniedException()` returns the response that it receives from your implementation of `AuthenticationRequiredHandlerInterface::onAuthenticationRequired()`. You can set the status code on the `Response` object that you create there.

**Comment by Charl13** [comment]
Thanks for your swift response!

> How it should normally work: `ExceptionListener::handleAccessDeniedException()` returns the response that it receives from your implementation of `AuthenticationRequiredHandlerInterface::onAuthenticationRequired()`. You can set the status code on the Response object that you create there.

Let's zoom out a bit.

1. An authentication request is made
2. The user is successfully authenticated by Symfony's `JsonLoginAuthenticator`
3. An `AccessDeniedException` is thrown ([here](https://github.com/symfony/symfony/blob/1f15392fa1cedf02c65049b3d4506ab2a21e0463/src/Symfony/Component/Security/Http/Firewall/AccessListener.php#L126)) (my assumption is that the exception is thrown because 2FA is required).
4. The `ExceptionListener::handleAccessDeniedException()` kicks in and we're able to create a `Response` in `AuthenticationRequiredHandlerInterface::onAuthenticationRequired()` and modify it to our needs.
5. `ExceptionListener::handleAccessDeniedException()` takes the `Response` object from `AuthenticationRequiredHandlerInterface::onAuthenticationRequired()` and sets it in the `ExceptionEvent` which stops the event propagation.
6. Now here comes the important part: After the `kernel.exception` event (triggered [here](https://github.com/symfony/http-kernel/blob/6adf696d2ab97efc32438a62f305a0294c1aa773/HttpKernel.php#L213)) the `HttpKernel::handleThrowable()` will set the response to `500` if one of the following criteria didn't match: `$event->isAllowingCustomResponseCode()`, `$response->isClientError()`, `$response->isServerError()`, `$response->isRedirect()`.

So in my understanding it's not possible to return a `2xx` HTTP status code in the `Response` object created in `AuthenticationRequiredHandlerInterface::onAuthenticationRequired()` because this only kicks in on `kernel.exception`.

A workaround was to create an event subscriber with a priority higher then `Scheb\TwoFactorBundle\Security\Http\Firewall\ExceptionListener::onKernelException()` (because of the stop of the event propagation) which does `$event->allowCustomResponseCode()` under specific circumstances but if my theory is correct this should either be done by the `ExceptionListener::handleAccessDeniedException()` or at least be documented 🙂.

**Comment by scheb** [comment]
I was indeed able to reproduce this issue and, as you already hinted, `allowCustomResponseCode` has to be set on the event to make things work properly. Obviosuly Symfony is doing the very same thing on its [firewall expection listener](https://github.com/symfony/symfony/blob/9c3bdb7bdea986586213c7f5c897baf49e2d46ba/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L128). So I went ahead and published new releases 5.13.2 and 6.0.2 to include this fix.

Thanks for this very thorough analysis of the issue. Helped a lot to reproduce anf fix it.
