### ISSUE TITLE
Bypassing 2FA When using Symfony Login Link

### ISSUE THREAD

**Issue by bernard-ng** [scheb/2fa#139]
**description**
For a while now symfony offers the possibility to connect without password, using the login link feature. In my application I use this feature and other authenticators, it is possible to bypass the 2fa verification when I connect with oauth for example by adding this in my authenticator:

```php
public function createAuthenticatedToken(PassportInterface $passport, string $firewallName): TokenInterface
{
    $token = parent::createAuthenticatedToken($passport, $firewallName);

    // Set this to bypass 2fa for this authenticator
    $token->setAttribute(TwoFactorAuthenticator::FLAG_2FA_COMPLETE, true);

    return $token;
}
```

however i didn't find the way to do the same, if the user connects via login link, is it possible ? do you have a guidance to give me ?
I think it would be a good feature to add

**Comment by scheb** [comment]
I haven't tested it, but the follwing should do the job:

- Create and register a [custom condition](https://symfony.com/bundles/SchebTwoFactorBundle/6.x/custom_conditions.html)
- Check if the passport was a `SelfValidatingPassport`, which is used for the link-login procedure. You get that from the `$context` object. If it is, skip 2fa by returning `false`

Note: This requires bundle version 6 to work.

**Comment by bernard-ng** [comment]
Thank you for the guide, I have solved my problem. one important thing is to be careful not to have an `Authenticator` that generates a `SelfValidatingpassport` otherwise the 2fa verification will also be bypassed

```php
final class TwoFactorCondition implements TwoFactorConditionInterface
{
    public function shouldPerformTwoFactorAuthentication(AuthenticationContextInterface $context): bool
    {
        if ($context->getPassport() instanceof SelfValidatingPassport) {
            return false;
        }
        return true;
    }
}
```
