### ISSUE TITLE
After login the page isn't working at the moment and redirected too many times error is shown.

### ISSUE THREAD

**Issue by ravendraivy** [scheb/2fa#140]
Hi,
I have followed the all steps which are on document but still facing the issue my symfony version which upgraded from 3.4 to 4.4 and my 2fa version are "scheb/2fa-bundle": "^5.13","scheb/2fa-google-authenticator": "^5.13","scheb/2fa-qr-code": "5.13.2".
I have attached the error screenshot so please have a look and guide me.

<img width="1440" alt="Screenshot 2022-04-27 at 11 13 18 PM" src="https://user-images.githubusercontent.com/87407822/165588990-dbdb53f6-7d9a-446f-9ab6-22021c41be21.png">

**Comment by scheb** [comment]
Please change `access_control` so that the `- { path: ^/, roles: IS_AUTHENTICATED_FULLY }` rule comes last. These rules are evaluated in order, so the `^/` always matches and the `^/2fa` rule is never reached.

**Comment by ravendraivy** [comment]
Thanks a lot. its now worked but when I am trying to scan the QR from my google authenticator app. The app is showing me "key not recognised" error message.

**Comment by scheb** [comment]
Hard to tell, because I don't know how you generate that QR code. I'd recommend, print out the raw QR code content and see what you get. I'd that looks reasonable. This is definitely not a bundle problem, but something with how the code is rendered.

**Comment by ravendraivy** [comment]
**Below the method to generate the qrCode** 
```
/**
     * @Route("/2fa", name="2fa_login", schemes={"https"})
     */

    public function check2faAction(GoogleAuthenticatorInterface $authenticator, TokenStorageInterface $storage, QrCodeGenerator $qrCodeGenerator){
        $code = $authenticator->getQRContent($storage->getToken()->getUser());
        $qrImageCode =  $qrCodeGenerator->getGoogleAuthenticatorQrCode($storage->getToken()->getUser());
        $qrCode = "https://chart.googleapis.com/chart?cht=qr&chs=150x150&chl=".$code;
        return $this->render('security/2fa_login.html.twig',[
            "qrCode" => $qrCode,
            "qrImageCode" => $qrImageCode->writeString()
        ]);
    }
```
**Its image where qr being display**
`<img id="imageQRcode" src="{{ qrCode }}" alt="QR Code" name="imageQRcode" />`

**There is raw data of the QR code**
`https://chart.googleapis.com/chart?cht=qr&chs=150x150&chl=otpauth://totp/Ravendra%20Payasi%3Atest%40test.com%40Local.test?issuer=Ravendra%20Payasi&secret=7TAZX4A7CHJHTALFYJ3GN4ETQZQGIYVACJPGBBM4EG3PAXAGPEBQ`

**And I am using email instead of username in the User entity method** 
```
public function getGoogleAuthenticatorUsername(): string
    {
        return $this->email;
    }
```

**Comment by scheb** [comment]
You should `urlencode()` the `$code` value that you put into the URL

**Comment by ravendraivy** [comment]
Thanks a lot. how I can override the "2fa_check" method which being send on the 2fa check form. and wanted to add validation if entered value is wrong then display the proper error message.

**Comment by scheb** [comment]
Err, I don't understand that question

**Comment by ravendraivy** [comment]
![https___127 0 0 1_8001_2fa](https://user-images.githubusercontent.com/87407822/165628692-81e40bf6-720e-45b4-811d-38e392a6d030.png)
On above image you can see the input where we enter the value to authenticate the 2fa. but if I entered wrong value which is not on the google authenticator app and clicked on the login button then its not showing me any error message and I wanted to display error message that "**You have entered the wrong value**".
**You can see below the 2fa form** 
that's why I want to override **2fa_check**  method which is added on form action. 
```
<form class="form" action="/2fa_check" method="post">
    <p class="widget">
        <input
            id="_auth_code"
            type="text"
            name="_auth_code"
            autocomplete="one-time-code"
            autofocus
                    />
    </p>

            <p class="submit"><input type="submit" value="Login" /></p>
</form>
```

**Comment by scheb** [comment]
No, you don't what to overwrite the 2fa_check method, then you'd need to build all the 2fa code checking logic yourself.

What you want is adding the code to display the error message to your template. Check the default template how this is done: https://github.com/scheb/2fa/blob/6.x/src/bundle/Resources/views/Authentication/form.html.twig#L7:L9
