### ISSUE TITLE
Session changes and 2fa fails

### ISSUE THREAD

**Issue by devigner** [scheb/2fa#143]
**Bundle version**: 6.0.2
**Symfony version**: 6.0.8
**PHP version**: 8.1.6
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

*** Problem/Solution 1 ***
I'm writing an API. Because we need 2fa it is not stateless (question 2). 
I have followed the instructions to get everything working. But after
the 2fa auth code is approved the session appears to be corrupt.

The session after it is authorized is based upon 
`Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\Token\JWTPostAuthenticationToken` with an attribute
flag `2fa_complete`. A request later the session is wrapped inside `Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken`
but is missing the `2fa_complete` attribute. I'm new to the security system of symfony 6.

*** Problem/Solution 2 ***
As I really don't like the requirement of session and cookies and want my session to be stateless. 
I tried to get 2fa stateless working following this issue: https://github.com/scheb/2fa/issues/78 
but that issue is for symfony 5. Is there any documentation somewhere how to do this in symfony 6?

** My config: **

*** scheb_2fa.yaml ***

    scheb_two_factor:
        security_tokens:
            - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
            - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
            - Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\Token\JWTPostAuthenticationToken
    
        totp:
            enabled: true
            server_name: server.dev
            issuer: Somebody
            window: 10

*** security.yaml ***

    security:
        enable_authenticator_manager: true
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
        providers:
            jwt:
                entity:
                    class: App\Entity\User\User
                    property: email
    
        firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
    
            api:
                pattern: ^/
                stateless: false
                entry_point: jwt
                provider: jwt
                jwt: ~
                context: api_auth
                json_login:
                    check_path: api_login_check
                    username_path: email
                    password_path: password
                    success_handler: app.handler.authentication_success
                    failure_handler: lexik_jwt_authentication.handler.authentication_failure
                two_factor:
                    auth_form_path: /api/auth/2fa-login
                    check_path: /api/auth/2fa-login-check
                    multi_factor: true
                    prepare_on_login: true
                    prepare_on_access_denied: true
                    auth_code_parameter_name: data.authCode
                    authentication_required_handler: App\Security\TwoFactorAuthenticationRequiredHandler
                    success_handler: App\Security\TwoFactorAuthenticationSuccessHandler
                    failure_handler: App\Security\TwoFactorAuthenticationFailureHandler
                refresh_jwt:
                    check_path: api_refresh_token
                logout:
                    path: _security_logout
                    target: api_login_check
    
        role_hierarchy:
            ROLE_ADMIN:         [ROLE_INTERMEDIARY, ROLE_PROPERTY]
            ROLE_INTERMEDIARY:  ROLE_INTERMEDIARY_JUNIOR
            ROLE_SUPER_ADMIN:   ROLE_ADMIN
    
        access_control:
            - { path: ^/api/auth/login-check, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/token-refresh, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/reset-password, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/check-two-factor, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/set-two-factor, roles: PUBLIC_ACCESS }
            - { path: ^/api/session, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/qr, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/2fa-login, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
            - { path: ^/api/auth/2fa-login-check, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
            - { path: ^/_profiler, roles: PUBLIC_ACCESS }
            - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

*** framework.yaml ***
    
    framework:
        secret: '%env(APP_SECRET)%'
        csrf_protection: false
        http_method_override: false

        php_errors:
            log: false
    
        session:
            enabled: true
            use_cookies: true
            # ID of the service used for session storage
            # NULL means that Symfony uses PHP default session mechanism
            handler_id: '%env(REDIS_URL)%'
            cookie_secure: true
            cookie_samesite: lax
            cookie_lifetime: 360000
            cookie_path: '/'
            storage_factory_id: session.storage.factory.native

`
*** api-platform.yaml ***

    api_platform:
        path_segment_name_generator: api_platform.path_segment_name_generator.dash
        mapping:
            paths: [
                '%kernel.project_dir%/src/Entity',
                '%kernel.project_dir%/src/Entity/User',
            ]
        patch_formats:
            json: ['application/merge-patch+json']
            jsonapi: ['application/vnd.api+json']
        formats:
            json: ['application/json']
            jsonapi: ['application/vnd.api+json']
            jsonld: ['application/ld+json']
            html: ['text/html']
        swagger:
            versions: [3]
            api_keys:
                apiKey:
                    name: Authorization
                    type: header
        defaults:
            stateless: false
            # Good cache defaults
            cache_headers:
                vary: ['Content-Type', 'Authorization', 'Origin']

**Comment by scheb** [comment]
> *** Problem/Solution 1 *** I'm writing an API. Because we need 2fa it is not stateless (question 2). I have followed the instructions to get everything working. But after the 2fa auth code is approved the session appears to be corrupt.
> 
> The session after it is authorized is based upon `Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\Token\JWTPostAuthenticationToken` with an attribute flag `2fa_complete`. A request later the session is wrapped inside `Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken` but is missing the `2fa_complete` attribute. I'm new to the security system of symfony 6.

When you're saying "after it is authorized", does that mean "after 2fa has been successfully finished"?

> *** Problem/Solution 2 *** As I really don't like the requirement of session and cookies and want my session to be stateless. I tried to get 2fa stateless working following this issue: #78 but that issue is for symfony 5. Is there any documentation somewhere how to do this in symfony 6?

No, there's none. Any solution for 2fa in a stateless environment has always been messy, because 2fa as a concept requires a state. Somewhere you have to store wether an authentication process has been completed 2fa or not.

**Comment by devigner** [comment]
`When you're saying "after it is authorized", does that mean "after 2fa has been successfully finished"?`

After 2fa has authorized the request.

**Comment by scheb** [comment]
Well, that's weird, because that `2fa_complete` flag is exactly there to prevent you from falling back to a `TwoFactorToken`.

Would you please check if you're hitting this line of code, after completing 2fa: https://github.com/scheb/2fa/blob/2c5651e53b296405f2f86fef4f7fd1deb89f0322/src/bundle/Security/TwoFactor/Event/AuthenticationTokenListener.php#L59

Because then the question is, why doesn't this condition prevent it from going there 🤔 
https://github.com/scheb/2fa/blob/2c5651e53b296405f2f86fef4f7fd1deb89f0322/src/bundle/Security/TwoFactor/Event/AuthenticationTokenListener.php#L41-L44

**Comment by devigner** [comment]
I've stripped the whole process to two request. The 2fa secret is set with fixtures (I'm in a very early stage of the app). When I sign in (with the JWT login-check)  line 59 is executed (how do I include a piece of code?):

Which I think is correct. It has no 2fa flag, so that should be.

Second request with the JWT bearer and the body containing the authCode sets the `UsernamePasswordToken` inside the session with the 2fa_complete attribute.

Next request the `JWTPostAuthenticationToken` is there instead of the `UsernamePasswordToken`. 

This is probably the problem ...

**Comment by scheb** [comment]
Sorry for the late response, was busy the last days.

> I've stripped the whole process to two request. The 2fa secret is set with fixtures (I'm in a very early stage of the app). When I sign in (with the JWT login-check) line 59 is executed (how do I include a piece of code?):
> 
> Which I think is correct. It has no 2fa flag, so that should be.

Yes, so far everything as expected.

> Second request with the JWT bearer and the body containing the authCode sets the `UsernamePasswordToken` inside the session with the 2fa_complete attribute.

And that's also as expected.

> Next request the `JWTPostAuthenticationToken` is there instead of the `UsernamePasswordToken`.
> 
> This is probably the problem ...

Yea, at this point something weird is happening, but I cannot tell you what it is. Doesn't seem to be a mechanic from the 2fa-bundle, because it would have no reason to replace a `UsernamePasswordToken` with a 3rd-party `JWTPostAuthenticationToken`. You'd need to figure out where this token is coming from and then investigate further what code path is triggering the replacement of the token.

**Comment by devigner** [comment]
I was wondering about the tokens. Without the 2fa bundle the API was stateless and the application identifies the user with the JWT. With the 2fa bundle the user is still identified with the JWT but also with the session cookie. This smells like trouble :). I would think both can co exists but with Symfony's firewall it can become complex. It is not possible to have both tokens, am I right. So who comes first and why.

I will keep this issue up to date if I have updates.

**Comment by scheb** [comment]
I could imagine that after completing the 2fa process the authenticator of JWTAuthenticationBundle is kicking in and overwriting the security token with its own token. Authenticators have a priority and only one authenticator can be called in a request, so as long as you're in the intermediate "2fa incomplete" state, the 2fa-bundle authenticator probably has priority - until you complete 2fa authentication. Something like that I'd guess. But I have never heard of such a behavior before and you're not the first one using JWTAuthenticationBundle with 2fa-bundle.

Have a look at the security logs on the first request after completing 2fa. Maybe that helps to clear up what's happening.

**Comment by devigner** [comment]
I've been debugging the process. My setup is with three requests:

1. /login-check
    - Handled by JWTAuthenticationBundle
2. /2fa-login-check
    - Handled by SchebTwoFactorBundle
3. /api/some-route-that-is-behind-the-firewall
    - Here the token is not accepted

The security logs are returning the following in step 3:

        [2022-06-07T09:17:09.473886+00:00] security.DEBUG: Stored the security token in the session. {"key":"_security_api_auth"} []
        [2022-06-07T09:17:14.971608+00:00] security.DEBUG: Read existing security token from the session. {"key":"_security_api_auth","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
        [2022-06-07T09:17:15.131052+00:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"<redacted>"} []
        [2022-06-07T09:17:15.136619+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"api","authenticators":3} []
        [2022-06-07T09:17:15.136729+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"Scheb\\TwoFactorBundle\\Security\\Http\\Authenticator\\TwoFactorAuthenticator"} []
        [2022-06-07T09:17:15.136812+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"api","authenticator":"Scheb\\TwoFactorBundle\\Security\\Http\\Authenticator\\TwoFactorAuthenticator"} []
        [2022-06-07T09:17:15.136882+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Authenticator\\JWTAuthenticator"} []
        [2022-06-07T09:17:15.136986+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\JsonLoginAuthenticator"} []
        [2022-06-07T09:17:15.137074+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"api","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\JsonLoginAuthenticator"} []
        [2022-06-07T09:17:15.183191+00:00] security.DEBUG: Authenticator set no success response: request continues. {"authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Authenticator\\JWTAuthenticator"} []
        [2022-06-07T09:17:15.209412+00:00] security.DEBUG: Stored the security token in the session. {"key":"_security_api_auth"} []

**Comment by scheb** [comment]
This looks like JWTAuthenticator triggers and replaces the token:
```
    [2022-06-07T09:17:15.136882+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Authenticator\\JWTAuthenticator"} []
...
    [2022-06-07T09:17:15.183191+00:00] security.DEBUG: Authenticator set no success response: request continues. {"authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Authenticator\\JWTAuthenticator"} []
    [2022-06-07T09:17:15.209412+00:00] security.DEBUG: Stored the security token in the session. {"key":"_security_api_auth"} []
```

I'd recommend you check the profiler for that request, you'd typically get way more info from there.

**Comment by devigner** [comment]
How should it work? Which token should be stored in the session? How does the JWT and the session work together? It is still not clear to me.

**Comment by scheb** [comment]
Once 2fa was completed, the UsernamePasswordToken should be loaded and kept in the session. JWTAuthenticator shouldn't trigger, because in the session you're already authenticated, so no need to start another authentication process. But for some reason it does.

**Comment by devigner** [comment]
On every request the JWT needs to be decoded. That is why it should authenticate on every request. Changing this behavior feels rather strange. 

Would storing the 2fa_complete flag inside the JWT be a solution?

I'm trying to think of a reason to not to do it like that.

The flow would be something like this:
- signin returns JWT
- authenticate 2fa returns updated JWT with 2fa flag inside

**Comment by scheb** [comment]
> On every request the JWT needs to be decoded.

I had another look at your config, is that what this thing does? ->

```yaml
            refresh_jwt:
                check_path: api_refresh_token
```

If that's the case, well, then that's the problem. Once you've completed 2fa, on the next request, you're getting another authentication event, which is then starting another 2fa process. And so the cycle starts again.

I don't really see a reason why you need to do that on every request in a _stateful_ firewall - because the authentication state is persisted in the session across requests - but if that's what you want, you need to find a secure way to remember if you've completed 2fa before. So that subsequent authentication events from the refresher aren't starting another 2fa process.

Setting the `2fa_complete` on the security token would be one way to do it, the other one is described [here](https://symfony.com/bundles/SchebTwoFactorBundle/current/custom_conditions.html). But I can't tell you neither, how to store that information in the JWT token (if that's even possible), nor how to get it set on the security token that is created by the refresher logic, because these aren't my bundles.

**Comment by devigner** [comment]
I've stripped the whole process and also removed the other authenticators. JWT's are always decoded on every request because in "a normal" setup there is no session/state. I'm going to continue in finding a solution, thanks for the insights and the great bundle.

**Comment by oriiyx** [comment]
@devigner hey mate :)
I'm currently implementing 2fa with the same jwt bundle - were you able to complete the whole process implementing a stateless solution or should I rather focus on implementing it with states?
From what I read with your discussion with scheb - he's instigating that 2fa na jwt solutions work better with states - which sounds correct... just want to get another opinion

**Comment by leonwisdom** [comment]
@devigner & @oriiyx I’m currently trying to implement 2fa with jwt stateless but running into the same issues you both mentioned. Did either of you manage to get this working at all?

**Comment by oriiyx** [comment]
@leonwisdom 
I had to develop it with state - could not make it work otherwise

`stateless: false`

**Comment by devigner** [comment]
Hi, we switched to AWS Cognito (https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html) for authentication. My implementation is currently not open source but I can release it as anybody is interested

**Comment by PSarmidani-MIG** [comment]
I Had the same problem. `sameSite` should not be set to `lax` but to `none`.

This should work:

```
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    http_method_override: false

    php_errors:
        log: false

    session:
        cookie_samesite: none    # Allow cookies to be sent in cross-site requests
        cookie_secure: auto
        enabled: true
        use_cookies: true
        # ID of the service used for session storage
        # NULL means that Symfony uses PHP default session mechanism
        cookie_lifetime: 360000
        cookie_path: '/'
        storage_factory_id: session.storage.factory.native
```
