### ISSUE TITLE
Resending the auth code

### ISSUE THREAD

**Issue by TheAFOGroup** [scheb/2fa#145]
This is not a bug report but rather a question. I would like to offer a link/button for the user to re-sent the code if he didn't received it.

Upon checking https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/email.html#re-send-authentication-code I cannot understand how you can re-send the code from a custom route since it requires the $user interface.

Would you please offer a bit of example how to use this? Ideally I would like to add to the LoginController (which has just 2 routes, /login and /logout) another route say... /2fa-resend and that would be it.

At the moment I have created _src\Interface\LoginAuthCodeInterface_ where I send out a custom HTML email with the code (Mailer is a service).

```
<?php

namespace App\Interface;

use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;
use Scheb\TwoFactorBundle\Mailer\AuthCodeMailerInterface;
use App\Service\Mailer;

class LoginAuthCodeInterface implements AuthCodeMailerInterface
{
    private $mailer;

    public function __construct(Mailer $mailer)
    {
        $this->mailer = $mailer;
    }

    public function sendAuthCode(TwoFactorInterface $user): void
    {
        $authCode = $user->getEmailAuthCode();

        $this->mailer->send2Fa($authCode);
    }
}
```

Not sure if this helps with anything, just mentioning it.

Many thanks!

**Comment by scheb** [comment]
You can get the user object in your controller add described here: https://symfony.com/doc/current/security.html#fetching-the-user-object

In your controller, either inject or fetch `scheb_two_factor.security.email.code_generator` service and call the resend method with the user object.
