### ISSUE TITLE
Moving 2FA code from User entity to session

### ISSUE THREAD

**Issue by tybw** [scheb/2fa#146]
**Bundle version**: 6.0.2
**Symfony version**: 6.0
**PHP version**: 8.1
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**
This is a feature question. I have been using the bundle without any issue, which is great. I am not sure if the bundle support storing 2FA code in session. If it doesn't, is it a good idea to store the 2FA code in session instead of User object. It is because I would like to avoid an extra database update every time a user login. Moreover, I'm using Redis to store session for better performance and scalability. The idea of restricting the verification to a single session is to avoid anyone with the code get verified without being in the same browser session (I send 2FA code via email and am not using HTML form, so can't use CSRF, etc).

I have been trying to extend the bundle to add session support for the code, but it looks like I need to decorate quite a few services. The main blocker for me is `CheckTwoFactorCodeListener`.

Appreciate it very much in advance for any guidance, opinions and suggestions.

**Additional Context**

**Comment by scheb** [comment]
I'd refrain from hacking the bundle and overwriting private services.

The best thing to do would be to implement a [custom two-factor provider](https://symfony.com/doc/current/SchebTwoFactorBundle/providers/custom.html), then you can store the code wherever you like.

**Comment by tybw** [comment]
Thanks @scheb  for recommendation. 

What I was trying to do was to _decorate_ the services in the bundle, so I can extend them rather than rewrite them, since I was not doing anything unorthodox other than saving and retrieving the 2FA code from session.

I'll go down the path you suggested. Thanks!
