### ISSUE TITLE
scheb/2fa-qr-code Symfony6 support

### ISSUE THREAD

**Issue by hanishsingla** [scheb/2fa#152]
**Bundle version**: 6.0.2
**Symfony version**: 6.0.9

**Description**

Problem 1
    - scheb/2fa-qr-code v5.13.0 requires scheb/2fa-bundle v5.13.0 -> found scheb/2fa-bundle[v5.13.0] but the package is fixed to v6.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Problem 1
    - scheb/2fa-qr-code v5.13.0 requires scheb/2fa-bundle v5.13.0 -> found scheb/2fa-bundle[v5.13.0] but these were not loaded, likely because it conflicts with another require.
    - scheb/2fa-qr-code v5.13.1 requires scheb/2fa-bundle v5.13.1 -> found scheb/2fa-bundle[v5.13.1] but these were not loaded, likely because it conflicts with another require.
    - scheb/2fa-qr-code v5.13.2 requires scheb/2fa-bundle v5.13.2 -> found scheb/2fa-bundle[v5.13.2] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires scheb/2fa-qr-code ^5.13 -> satisfiable by scheb/2fa-qr-code[v5.13.0, v5.13.1, v5.13.2].

**Additional Context**

We are trying to setup 2FA on our Symfony6 project and for it, we have installed [2FA bundle](https://packagist.org/packages/scheb/2fa-bundle), now we are trying to setup [QR code generator bundle](https://packagist.org/packages/scheb/2fa-qr-code) which is still on v5.13.2 and requires 2FA bundle to be on v5

**Comment by scheb** [comment]
`scheb/2fa-qr-code` has been discontinued with bundle version 6, more information here, what to do instead:

https://github.com/scheb/2fa/blob/6.x/UPGRADE.md#scheb2fa-qr-code-package
