### ISSUE TITLE
2fa need to reauth

### ISSUE THREAD

**Issue by pyatnitsev** [scheb/2fa#160]
**Bundle version**: 6.2.0
**Symfony version**: 6.0.10
**PHP version**: 8.0.7
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

I have a truble with 2fa session, I create a custom auth provider and it works, but 2fa dialig sometimes showing to users (but main user session is alive)

How to increase ttl for 2fa?

**Additional Context**

**Comment by scheb** [comment]
There is no such thing as a TTL for 2fa.

You must have some authentication provider in your application, which is creating a new security token, which in effect starts a new authentication process.

Check the request right before the 2fa dialog is shown, if there was an authentication event. Check where that authentication event is coming from.
