### ISSUE TITLE
Add digest method in configuration 

### ISSUE THREAD

**Issue by sbarbo** [scheb/2fa#18]
Hi, in the GoogleTotpFactory:createTotpForUser method, the digest way is in hard 'sha1'.
Is it possible to put this value in the configuration, in the google section?

Thank you

**Comment by Spomky** [comment]
By using another hashing function, this won't be compatible with Google Authenticator or applications that do not support custom hashing functions.

This is already available. Please have a look at https://github.com/scheb/2fa/blob/5.x/doc/providers/totp.md

**Comment by sbarbo** [comment]
Ok, thank you, you're right, i use the totp and that's OK.
