### ISSUE TITLE
2FA form not shown upon successful login

### ISSUE THREAD

**Issue by tomazartack** [scheb/2fa#194]
I had to update an old project from Symfony 3 to latest Symfony 4, before we can make further updates towards the newest Symfony versions.... and in the composer file, one of the dependencies which I had to update was 2FA bundle as well.

I don't really need support, but just wanted to share my experience while using and updating this bundle from version 4.18 which was compatible with Symfony 3, to version 5.13 which is compatible with Symfony 4.4 and 5.

As I had the issue of the 2FA form not showing up upon successful login, I checked the documentation because it has a chapter of common issues. https://symfony.com/bundles/SchebTwoFactorBundle/5.x/troubleshooting.html#troubleshooting-2.
Here I ended up in point 2 -> No -> Unknown Issue, so it wasn't really that helpful.

Like said, my case was, I was updating the library from version 4.18 to 5.13, and version 5.13 introduced a new class - Scheb\TwoFactorBundle\Security\Http\Firewall\ExceptionListener with priority 2. Our application already had a similar exception listener with higher priority defined which got executed before and set the response object to the event, so the listener from this 2FA bundle no longer got called and the redirect to the 2fa form did not happen. Maybe the author of this bundle can add this example under troubleshooting point 2, to check if your application catches this exception first, and if the listener is called properly, in the documentation. I guess it might help a lot to somebody who has to do the same, because I spent many hours debugging in the security classes of Symfony and this bundle, to find this out.

Best regards,
Tomaz

**Comment by Chris53897** [comment]
@tomazartack Thanks for sharing your experience.
You can create a Fork and edit this file and make a PR.
https://github.com/scheb/2fa/blob/6.x/doc/troubleshooting.rst
