### ISSUE TITLE
Any plans to support Symfony 5.1 and the new enable_authenticator_manager option?

### ISSUE THREAD

**Issue by PhilETaylor** [scheb/2fa#20]
Any plans to support Symfony 5.1 and the new enable_authenticator_manager option?

Symfony 5.0 is now end of life, and I would love to keep up to date

**Comment by scheb** [comment]
Version 5 already supports the new authenticator system. Just switch it on, the bundle will automatically adapt.

**Comment by PhilETaylor** [comment]
For ages I was getting 

```
The argument "0" doesn't exist.
```

I somehow overcome that though ... not sure how... :) Thanks anyway

**Comment by PhilETaylor** [comment]
Im currently staring at this with a blank face - any help greatly appreciated! 

I get this Exception after submitting the totp value on login

<img width="1100" alt="Screenshot 2020-07-29 at 18 43 48" src="https://user-images.githubusercontent.com/400092/88834241-746ba780-d1cb-11ea-8f2c-a06cfb83d6b6.png">

**Comment by PhilETaylor** [comment]
Worked it out in the end, it was a routing issue... strange. Case closed.
