### ISSUE TITLE
Cannot install scheb/2fa-qr-code on a project with scheb/2fa-bundle version 6.9 (latest)

### ISSUE THREAD

**Issue by anthonyptetlow** [scheb/2fa#200]
**Bundle version**: 6.9
**Symfony version**: 6.2
**PHP version**: 8.2
**Using authenticators** (`enable_authenticator_manager: true`): YES / NO

**Description**
When trying to install the scheb/2fa-qr-code on a fresh install of the latest version of scheb/2fa-bundle (6.9) composer cannot resolve to an installable set of packages.  I think new tags just need released on the scheb/2fa-qr-code  for all versions of scheb/2fa-qr-code.

**To Reproduce**
1. in a new directory run `composer init`
2. then run `composer require scheb/2fa-bundle`
3. then run `composer require scheb/2fa-qr-code`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - scheb/2fa-qr-code v5.13.0 requires scheb/2fa-bundle v5.13.0 -> found scheb/2fa-bundle[v5.13.0] but it conflicts with your root composer.json require (^6.9).
    - scheb/2fa-qr-code v5.13.1 requires scheb/2fa-bundle v5.13.1 -> found scheb/2fa-bundle[v5.13.1] but it conflicts with your root composer.json require (^6.9).
    - scheb/2fa-qr-code v5.13.2 requires scheb/2fa-bundle v5.13.2 -> found scheb/2fa-bundle[v5.13.2] but it conflicts with your root composer.json require (^6.9).
    - Root composer.json requires scheb/2fa-qr-code ^5.13 -> satisfiable by scheb/2fa-qr-code[v5.13.0, v5.13.1, v5.13.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require scheb/2fa-qr-code:*" to figure out if any version is installable, or "composer require scheb/2fa-qr-code:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by scheb** [comment]
The qr code package is no longer available on version 6. It was discontinued, because it did not do much and maintaining it did not justify its benefit.

For information what to do instead, see: https://github.com/scheb/2fa/blob/6.x/UPGRADE.md#scheb2fa-qr-code-package

**Comment by anthonyptetlow** [comment]
Thanks for the response :-) Will do this.
