### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by Chris53897** [scheb/2fa#207]
Are there any plans to support symfony 7?
Should it be a new major version with `^6.4 || ^7.0` or  a 6.9.x version with `^5.4 || 6.0 || ^7.0` ?

I did not check how much work it is to upgrade to symfony 7.

**Comment by scheb** [comment]
Haven't checked yet. Will try to get a build running.

**Comment by scheb** [comment]
It's likely going to be a new major release, as Symfony 7 is introducing some breaking changes and from my experience too much effort implementing and maintaining the backwards compatibility layers.

**Comment by Chris53897** [comment]
i prefer a new major version, too.

**Comment by scheb** [comment]
May I ask why? Shouldn't make much of a difference for you as a user ;)

**Comment by Chris53897** [comment]
As a user yes. For a PR it is easier without BC Layers

**Comment by scheb** [comment]
For progress see #209
