### ISSUE TITLE
advice on taking this bundle to the next level

### ISSUE THREAD

**Issue by yard-mschwartz** [scheb/2fa#214]
**Bundle version**: latest
**Symfony version**: latest
**PHP version**: latest

**Description**

I'm sorry if this is not the right place to ask, but I didn't really know where else to go.

I'm trying to use your amazing bundle in order to create a bundle of my own. Our company is looking to standardize certain components of our applications, so we don't invent the wheel with every new project.

One of the first tasks I took on was to standardize our login functionality, including the availability of 2FA by email or by using the Google authenticator. Additionally, my idea is to overwrite certain config settings by our standardized values.

I watched the tutorial on Symfonycasts on writing your own bundles, which was written for Symfony 4. In addition I studied the documentation of Symfony 6 and I studied other bundles to see how they set-up their configuration.

Yet, there are so many different ways of doing things that it's hard to get everything right. There is documentation pointing you to old (wrong) ways to configure your bundle, but there are also (multiple) correct ways of configuring your bundle. I keep hitting walls, where there seems to be missing one piece of the puzzle every time I try to move some logic to a bundle. I don't really understand much of how Symfony works under the hood, nor do (m)any of my colleagues.

Do you maybe have any piece of advice on how to get to the level where creating your own bundles becomes routine? How did you yourself become so knowledgeable that you were able to create this bundle? I'd love to hear your suggestions.

**Comment by nicodemuz** [comment]
@yard-mschwartz you should maybe mention the reasoning why you're considering to (re)create your own bundle. Which features are missing that require you to use your own bundle?

Likely the easiest way to adapt this bundle to work for your use case is to use the forking feature of GitHub.

**Comment by scheb** [comment]
I'm also wondering why you'd want to rewrite the whole bundle. It's likely doing everything you need and it has lots of extension points for customization.

On the question, how do you get good at creating bundles: with a lot of practice ;). My recommendation would be, start with something simple and work yourself towards more complex features. Starting with a security-related bundle is definitely _not_ simple. Symfony's security system is one of the most complex parts of the framework and wrapping your head around it will take time and you'd need to master the basics of bundle creation (service definition, configuration, dependency injection) first.

If you're looking for help on your journey, the Symfony Slack community is a pretty good place to start. Lot of knowledgeable people, including the Symfony core developers, are hanging out there.

**Comment by yard-mschwartz** [comment]
Sorry for wording my post poorly. I am definitely not aiming to rewrite the bundle. I would like to use specific features of your bundle by writing a bundle on top to preconfigure a lot of things. The bundle is going to have an abstract base user that supports two types of 2FA and has the `Timestampable` trait. It will have authentication success and failure handlers, etc. It will (ideally) have routes for login, logout, password reset, etc. It will (ideally) override some of the default config provided by other bundles. Just so we don't have to do a lot of the same work with every project we do.

Decided to take a dive into the framework last Friday, when login wasn't working despite password login and 2FA login being successful. Turns out you shouldn't include the `password` field in `eraseCredentials()`, because it will then appear to Symfony that the user changed his password when refreshed.

Thanks for the advice! I'll try not to start with the hardest parts first.
