### ISSUE TITLE
Reduce the secret length to 16 characters

### ISSUE THREAD

**Issue by parithibang** [scheb/2fa#222]
I appreciate the package for implementing 2FA. 

This package is integrated into my application, and it functions properly. In one of my scenarios, the user may have desktop and mobile QR code applications. They can scan the QR code with the mobile device, which is OK. However, in case it's a desktop, I could have to create the secret and show it on the screen, which presently has 52 characters. Is it possible to set this to 16 characters?

Code Reference

Google Authenticator: https://github.com/scheb/2fa/blob/7.x/src/google-authenticator/Security/TwoFactor/Provider/Google/GoogleAuthenticator.php#L42-L45

`
public function generateSecret(): string
    {
        return Base32::encodeUpperUnpadded(random_bytes(32));
    }
`

**Comment by scheb** [comment]
Use `substr` to limit the secret to whatever length you want. That helper function is just meant to provide you a randomized value. It's up to you to decide what to do with it 🤷
