### ISSUE TITLE
Support locale with route

### ISSUE THREAD

**Issue by Mecanik** [scheb/2fa#243]
**Bundle version**: 7.5.0
**Symfony version**: 7.1
**PHP version**: 8.2

**Description**

I am trying to add locale to the route of /2fa, but unfortunately this is not accepted. For example, I tried something like:

scheb_2fa.yaml
```
2fa_login:
  path: /{_locale}/2fa
  defaults:
    _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
  path: /{_locale}/2fa_check
```

security.yaml
```
      two_factor:
        auth_form_path: /{_locale}/2fa # Path or route name of the two-factor form
        check_path: /{_locale}/2fa_check # Path or route name of the two-factor code check
```

But it does not receive the locale parameter, so it ends up like: `/%7B_locale%7D/2fa`

Is this possible at all?

Thanks

**Comment by scheb** [comment]
Use the name of the route `2fa_login` in the config. That should do the job.

For the check route I'm not so sure of that approach will work. Though it's not necessary to localize that route, nothing is ever shown on that route, it only does redirects.

**Comment by Mecanik** [comment]
> Use the name of the route `2fa_login` in the config. That should do the job.
> 
> For the check route I'm not so sure of that approach will work. Though it's not necessary to localize that route, nothing is ever shown on that route, it only does redirects.

Unfortunately I don't understand what you mean.

**Comment by scheb** [comment]
Do this: 
```
      two_factor:
        auth_form_path: 2fa_login
        check_path: 2fa_login_check
```

**Comment by Mecanik** [comment]
> Do this:
> 
> ```
>       two_factor:
>         auth_form_path: 2fa_login
>         check_path: 2fa_login_check
> ```

Thank you, this worked.
