### ISSUE TITLE
No authcode when rendering the template form

### ISSUE THREAD

**Issue by dchevilletRDR** [scheb/2fa#247]
**Bundle version**: 6.12
**Symfony version**: 5.4.41
**PHP version**: 8.3

Hi,
I'm trying to display the auth code in 2fa form like this 
{{ app.user.authCode }}
But in the first display it's the old code which is rendering. I refresh the page and now I have the new one.

I'm doing this only in dev environnement to avoid check email and copy/paste the code.
I know it's possible to have trusted device or IP, but this not what I want. 
I think this is a normal behaviour because the user object not already flush in database but I'm not sure and I want to know if it is possible to display the correct code without having to refresh the page.

I hope someone can help me

**Comment by scheb** [comment]
It is not possible to show the current auth code, because the auth code is generated _after_ the form has been rendered, with the `kernel.response` event. You could load the auth-code asynchronously in a separate request.

**Comment by dchevilletRDR** [comment]
Hello,
Thank you for your answer and your time.
have a nice day
