### ISSUE TITLE
Help to understand the "User is not in a two-factor authentication process" error

### ISSUE THREAD

**Issue by sdespont** [scheb/2fa#248]
Hi @scheb 

I regularly get the error “`User is not in a two-factor authentication process`” in my server logs from this library when my users try to log in and I don't understand what they're doing to get this error. I thought they had a favorite link with the 2fa_login_check route and clicked on it when they were already logged in, but it's an HTTP 403 error in this case.

Can you help me understand how this error occurs?

**Comment by scheb** [comment]
The error "User is not in a two-factor authentication process" happens, when a user tries to access a route that is protected by `IS_AUTHENTICATED_2FA_IN_PROGRESS`, but they're currently not in the middle of a 2fa process.
