### ISSUE TITLE
Redirect to referer after 2FA success

### ISSUE THREAD

**Issue by chaours** [scheb/2fa#251]
**Bundle version**: 7.5.0
**Symfony version**: 6.4.12
**PHP version**: 8.2.23

**Description**
I'm trying to redirect to the original referer. We tested to write a listener to store the referer original value through the 2fa-process but I think we can do it easier.

**Additional Context**
I think the solution could be around this option inside security.yaml => `default_target_path: referer` but the value referer don't exist i think.
Have you a solution for us ? Could we write a PR to help you on that ?

Thanks a lot !
Misha

**Comment by scheb** [comment]
Redirecting to the "referrer" (the page the user tried to access, before being redirected to login) is the standard behavior of the bundle. You don't need to configure anything for that, no need to configure `default_target_path` for that.

If you want to redirect to a specific URL, you can overwrite the session attribute `'_security.'.$firewallName.'.target_path'`.

**Comment by chaours** [comment]
Thanks for your answer. Hmm... in our project this is not the default behavior. I need to check in more detail... Do you have any idea to explain this bad behavior?

**Comment by scheb** [comment]
The repository contains this little test application https://github.com/scheb/2fa/tree/7.x/app that I used to verify the behavior. Could help to to compare what the differences are.
