### ISSUE TITLE
Composer install warning

### ISSUE THREAD

**Issue by christianostrem** [scheb/2fa#26]
- Installing scheb/2fa-qr-code (v5.1.1): Loading from cache

Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.

I dont know where I should post this. issue.

**Comment by scheb** [comment]
These are not direct dependencies of `scheb/2fa-qr-code`, so they must be pulled in from some other dependency. If I start with a fresh new project and install `scheb/2fa-qr-code` I don't get any of these pulled in. Therefore I'd guess you have a package in your project at a certain version that forces these to be pulled in. To find out where these requirements are coming from you can run:

```
composer why twig/extensions
composer why zendframework/zend-code
composer why zendframework/zend-eventmanager
```

These should show you the chain of requirements and ultimately which package is pulling these in.

**Comment by christianostrem** [comment]
You are absolutely right. It is a dependency of ocramius/proxy-manager -> doctrine 
I just assumed that is came after: Installing scheb/2fa-qr-code and therefor it was connected to that libary. It seems i learned something new. Thanks for a quick response :)
