### ISSUE TITLE
Installing 2 factor

### ISSUE THREAD

**Issue by christianostrem** [scheb/2fa#27]
**Bundle version**: 5.1
**Symfony version**: 5.1.7

**Description**
My symfony craches with no error.
In my php error log on the server i get this error.

There is no extension able to load the configuration for "scheb_two_factor" in /config/packages/scheb_two_factor.yaml"
Looked for namespace "scheb_two_factor" Looked for namespace "scheb_two_factor", found ""framework", "sensio_framework_extra", "doctrine", "doctrine_migrations", "security", ..........

**Comment by scheb** [comment]
The bundle isn't loaded, you most likely forgot this step: https://github.com/scheb/2fa/blob/5.x/doc/installation.md#step-2-enable-the-bundle

**Comment by christianostrem** [comment]
I didn't skip it, but it did fail to upload to the server and therefore not working. Thanx again !!!
