### ISSUE TITLE
Integrate bundle with new Symfony 5.2 features

### ISSUE THREAD

**Issue by scheb** [scheb/2fa#29]
Symfony 5.2 contains multiple of my pull requests, which allow for a way less hacky integration with Symfony security.

https://github.com/symfony/symfony/pull/37336 and https://github.com/symfony/symfony/pull/37337
To replace the hacky `AccessListenerCompilerPass` for injecting a firewall-level listener at the right position. Keep `AccessListenerCompilerPass` for backwards compatibility with Symfony versions < 5.2.

https://github.com/symfony/symfony/pull/37359
Affects only the experimental "authenticator" system. Replace `AuthenticatorDecoratorCompilerPass`, hook into the new `AuthenticationTokenCreatedEvent` instead to replace the security token with a `TwoFactorToken`. The bundle's minimum supported Symfony version for using the new authenticator system will become 5.2 then, as I'm not intending to keep the existing Symfony 5.1 integration (it's an experiemental feature, so BC breaks are to be expected).

TODO: Remove entry point workaround, when Symfony 5.2.1 is released.

**Comment by PhilETaylor** [comment]
Is there an upgrade path document to scheb/2fa 5.2?

**Comment by scheb** [comment]
There are no changes necessary to upgrade. It should all just work fine.

**Comment by PhilETaylor** [comment]
It doesn't :-(

**Comment by PhilETaylor** [comment]
Im trying to debug to get something helpful instead of just complain gin "it doesn't work" :-) 

At the moment I have got to the error 

>"The two-factor provider "totp" has not been prepared."

after debugging "An authentication exception occurred."

**Comment by scheb** [comment]
@PhilETaylor Looks like there's something wrong with the preparation step, respecitively the event that the bundle is listening to. We'd need to dig deeper to find out what's going on.

Would you please open your own issue, so we have a place the track your problem? Please do not use the other person's thread, as it'll be super-confusing for you, me and the other person if we're mixing our debugging efforts.

**Comment by PhilETaylor** [comment]
yeah no worries - ok Im a dick. Running 5.1.4 and Symfony 5.2.0 on PHP 8 and its broken on attempting to authenticate the totp code :( back to the drawing board for me in debugging if this is Symfony 5.2 or PHP 8. Im using new authenticators. I'll be quiet until I have something to contribute that's not just a +1 :)

**Comment by scheb** [comment]
> Im using new authenticators

This is an important note, as authenticators are still experimental and its implementation is changing a lot. I was talking to Wouter yesterday, because I was also running into some authenticators-related issues, and they've already discovered some new problems in Symfony 5.2 and fixes are on the way to be released with Symfony 5.2.1 soon.

But still, it's *experimental* and it's not intended for production use. While the bundle has support for the authenticators system, the same applies, also the bundle's support is experimental and the implementation changes a lot (the whole reason for this issue here).

**Comment by PhilETaylor** [comment]
Fixed my issue! My firewall, which runs perfectly and has been like this for a long time, was missing a `pattern: /` 

The clue that lead me to this was in the installation docs where it states: 

>  The routes must be located within the path of the firewall, the one which uses two-factor authentication.

There is no "path" for Symfony 5.2, but by adding a pattern I was then able to use all 2fa features again.. very very very strange.

**Comment by scheb** [comment]
That's in fact a typo, `pattern` is also what I mean with "path". I'll change this in the docs.

**Comment by PhilETaylor** [comment]
Thanks for your support. My Symfony 5.2 app will be going live over Christmas to replace the Symfony 4 app - I appreciate your work!

**Comment by scheb** [comment]
Make sure you're using the newly released Symfony 5.2.1. That version contains some bug fixes related to the new authenticators system. That's the reason why I closed this issue just now, as I've verified that under Symfony 5.2.1 the bundle is working as expected - without any workarounds.

Have a great Christmas holiday!

**Comment by PhilETaylor** [comment]
Always, I "update everything every morning over the first coffee of the day" :) 

Even got PHP 8.0.2-dev compiled from source haha :-)

**Comment by scheb** [comment]
Haha, you should switch to Symfony 5.x-dev for maximum "living on the edge" experience ;)

**Comment by PhilETaylor** [comment]
Only on Sundays :)
