### ISSUE TITLE
PHP 8.0 build

### ISSUE THREAD

**Issue by scheb** [scheb/2fa#30]
Add a proper build on PHP8.0 (not nightly) as soon as it's released and made available on Travis-CI.

**Comment by stephanvierkant** [comment]
Do you expect any issues with the library? I've seen libraries using Match as an class name, which isn't allowed anymore (terrible upgrade path experience btw).

**Comment by scheb** [comment]
No, I don't expect any issues. The library is already building successfully with the nightly version of PHP8, including integration tests, which effectively run a whole Symfony application. 

This issue is just a reminder for myself, to add a PHP8 build as soon as Travis-CI makes an environment with a stable PHP8 version available.

**Comment by scheb** [comment]
Blocker for migrating to Github Actions: https://github.com/actions/runner/issues/2347
