### ISSUE TITLE
Limit unsuccessful logins 

### ISSUE THREAD

**Issue by sadortun** [scheb/2fa#35]
Hi,

Would it be possible to add a configuration option that would limit the number of invalid login within a time period ? Since the bundle is already managing security and login it would.make sense to add this feature.

Have a great day,
Samuel

**Comment by scheb** [comment]
You can already do this: https://github.com/scheb/2fa/blob/5.x/doc/brute_force_protection.md

**Comment by sadortun** [comment]
@scheb  You're awesome !!!
