### ISSUE TITLE
2fa stopped working after upgrade to symfony 5.2

### ISSUE THREAD

**Issue by dirkkredler** [scheb/2fa#38]
**Bundle version**: 5.2.0
**Symfony version**: 5.2.0

**Description**
After upgrading from Symfony 5.1.9 to Symfony 5.2.0 the 2fa stopped working:

two-factor-auth via email: 
- no token is generated
- no email is send

two-factor-auth via google authenticator:
- token is never accepeted as valid token

After downgrading to Symfony 5.1.9 everything started to work as before.

Are there any configuration changes needed for symfony 5.2.0? I am not sure if this behavior is a bug, or some configuration i need to adjust for Symfony 5.2.0. 

Thank you!!

**Comment by PhilETaylor** [comment]
It was all working in Symfony 5.2 until I upgraded to 5.2 of this bundle - now Im trying to get my head around what has broken ... currently at the error: 

with two-factor-auth via google authenticator:
> The two-factor provider "totp" has not been prepared.

**Comment by dirkkredler** [comment]
The Bundle Version 5.2.0 works for me with Symfony 5.1.9; in my case i think the breaking change is introduced with Symfony 5.2 or the combination of both: Symfony 5.2.0 with the Bundle 5.2.0? I do not see any error messages at all in the logs; it seems the 2fa-token is just not generated.

**Comment by PhilETaylor** [comment]
Im using 5.2.0/5.2.0 and I was able to generate a qr - scan it - but now not able to login with generic "An authentication exception occurred."... im debugging now :(

**Comment by scheb** [comment]
Well that's odd. When running my test application, In not having that issue. So we'd need to find out what's special about your application and causing the issue.

@dirkkredler
Which security system are you using? Classic security or the new authenticators system?

Would you please:
- Post your security.yaml config
- Downgrade The **bundle** to 5.1.4 and keep **Symfony** at 5.2.0 and see if you're still having issues. That way we can check if the behavioral change is caused by Symfony or the bundle.

**Comment by PhilETaylor** [comment]
Also of note: I run PHP 8 ;-)

**Comment by dirkkredler** [comment]
> Which security system are you using? Classic security or the new authenticators system?

I am using the guard-based authentication

> * Post your security.yaml config
`security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            access_denied_url: /login
            two_factor:
                auth_form_path: 2fa_login # The route name you have used in the routes.yaml
                check_path: 2fa_login_check # The route name you have used in the routes.yaml
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/profil/benutzer, roles: [ROLE_ADMIN], requires_channel: https }
        - { path: ^/profil, roles: [ROLE_USER, ROLE_ADMIN], requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
`

> * Downgrade The**bundle** to 5.1.4 and keep **Symfony** at 5.2.0 and see if you're still having issues. That way we can check if the behavioral change is caused by Symfony or the bundle.

I upgrade Symfony to 5.2.0 and downgraded your bundle to 5.1.4: no token is created 

Thank you!!

**Comment by dirkkredler** [comment]
> Which security system are you using? Classic security or the new authenticators system?

I am using the guard-based authentication

> * Post your security.yaml config

[security.yaml and scheb_two_factor config](https://gist.github.com/dirkkredler/5a7683024ac64358e434d981816d0443)

> * Downgrade The**bundle** to 5.1.4 and keep **Symfony** at 5.2.0 and see if you're still having issues. That way we can check if the behavioral change is caused by Symfony or the bundle.

Done, 2fa still broken in my setup.



thank you very much for your time and help, and the bundle of course :+1:

**Comment by scheb** [comment]
I notice there is no `pattern` defined for your `main` firewall. @PhilETaylor just told me in the other thread, that adding `pattern: /` was fixing it for him. So I'd suggest you try that before we dig any deeper.

**Comment by dirkkredler** [comment]
Yeah, i don't think we need it here, but anyway, i added the pattern to the main firewall, cleared the cache and it stays the same. If i select the user in the database, i see that there is no token generated.

You can postpone this issue for now, i will look into this later this week and try to debug the issue to a deeper level, so i can provide you more information. At the moment i don't see any BC in Symfony 5.2.0 or changes that would affect my app.

**Comment by PhilETaylor** [comment]
lazy! https://github.com/scheb/2fa/issues/39 ?

**Comment by dirkkredler** [comment]
@PhilETaylor yeah, setting `lazy: false` fixes the issue :+1:

**Comment by dirkkredler** [comment]
please see [ #39](https://github.com/scheb/2fa/issues/39)

**Comment by scheb** [comment]
v5.2.1 released to fix issues related to lazy firewalls.
