### ISSUE TITLE
Not redirecting to 2fa form when firewall is lazy

### ISSUE THREAD

**Issue by scheb** [scheb/2fa#40]
**Bundle version**: 5.x
**Symfony version**: 5.1
**PHP version**: Any
**Using authenticators** (`enable_authenticator_manager: true`): No

**Description**

When the lazy option is enabled on the firewall, 2fa-bundle potentially fails to redirect the user to the 2fa form.

**Comment by scheb** [comment]
v5.2.1 released to fix issues related to lazy firewalls.

**Comment by PhilETaylor** [comment]
Something strange going on here now... Im hitting an exception "User is in a two-factor authentication process" which doesn't show to the screen, but is being logged by Sentry... and the $attributes passed to `isPubliclyAccessAttribute` are only my custom role names and never PUBLIC_ACCESS or IS_AUTHENTICATED_ANONYMOUSLY
