### ISSUE TITLE
Mark scheb/two-factor-bundle as abandoned on Packagist

### ISSUE THREAD

**Issue by wouterj** [scheb/2fa#46]
I think it's a good idea to mark https://packagist.org/packages/scheb/two-factor-bundle as abandoned and suggest `scheb/2fa-bundle` instead.

We're always updating our dependencies based on `composer outdated --direct` and didn't catch the rename, as the old package didn't receive new releases (so we were still at 4.x). I only just discovered when my contribution wasn't visible in our project. Abandoned packages are shown by `composer outdated`.

**Comment by scheb** [comment]
I didn't do it (yet) because to my understanding "abandoned" means it's dead and effectively locked, but two-factor-bundle might still receive security fixes until its EOL in November.

Do you know if for abandoned packages you can still publish releases on Packagist?

**Comment by wouterj** [comment]
Ah. Seems like it's common to not mark it as abandoned until it reaches EOL (see also e.g. https://github.com/guzzle/guzzle3/issues/59 ). Sorry, didn't look at your support policy before posting the issue.

**Comment by scheb** [comment]
Yea, that's also my understanding of "abandoned" on Packagist. So I'm going to postpone this until EOL has been reached.
