### ISSUE TITLE
BC break in 5.4.0 release

### ISSUE THREAD

**Issue by richardhj** [scheb/2fa#51]
**Bundle version**: 5.4.0

**Description**

Hi @scheb, it looks like that the 5.4.0 release introduces a BC break because of the added constructor argument to the `TwoFactorFirewallConfig`.

Instantiating the class will break when using the old signature with 3 arguments instead of 4.

This issue occurred in the Contao CMS. For more context, please have a look at contao/contao#2680

For the Contao CMS, we already added a `conflict` to the composer.json to prevent installing the 5.4.0 from now and we will roll out a fix soon, so there won't be any long-term issues.
However, if you consider this issue as severe, maybe we can bring a fix into scheb/2fa? 😊

**Comment by scheb** [comment]
Well, that comes unexpected. I did not anticipate such a use-case with instance creations in foreign code, when it's actually the bundle's job to do that.

I could make the new parameter in `TwoFactorFirewallConfig` optional, so instance creation with 3 arguments would still work.

**Comment by scheb** [comment]
v5.4.1 with a BC fix released.

Also added some comments on your PR contao/contao#2680. A bit out of scope for the PR, which aims to fix the BC issue, but I wanted to let you guys know about some things that could be improved.

**Comment by richardhj** [comment]
Much appreciated! Thanks a lot @scheb!
