### ISSUE TITLE
Enable 2FA form?

### ISSUE THREAD

**Issue by meiyasan** [scheb/2fa#53]
**Bundle version**: latest
**Symfony version**: 5.2
**PHP version**: 7.4

Hello,

I am trying to setup your bundle, but it seems I am facing some configuration issues.
Basically, I want to enable the TOTP algo, but I don't understand which file you are talking about in [https://github.com/scheb/2fa/blob/5.x/doc/providers/totp.md](https://github.com/scheb/2fa/blob/5.x/doc/providers/totp.md) ?
Is it something like a file to create ./config/packages/scheb_2fa.yaml (should I still use the parameter of your old bundle scheb_two_factor)? Anyhow, it is not referenced by flex. So should I create something myself ?

Additionally, I tried to access the controller behind my route: /login/2fa
It says "User is not in a two-factor authentication process.". 
I know it is one of the FAQ issue, but I have no clue where is the form to enable this access for my user. (I tried to add a dummy totpSecret in my database for a given user, but it didn't work )
Is there something already prepared like a ready-to-use layout/form ?

Thanks a lot for your feedback

**Comment by scheb** [comment]
> Basically, I want to enable the TOTP algo, but I don't understand which file you are talking about in https://github.com/scheb/2fa/blob/5.x/doc/providers/totp.md ?
> Is it something like a file to create ./config/packages/scheb_2fa.yaml (should I still use the parameter of your old bundle scheb_two_factor)? Anyhow, it is not referenced by flex. So should I create something myself ?

If it hasn't been automatically created, create a `config/packages/scheb_2fa.yaml` yourself. The config node is `scheb_two_factor` as the bundle is still called `SchebTwoFactorBundle` in the PHP code.

> Additionally, I tried to access the controller behind my route: /login/2fa
> It says "User is not in a two-factor authentication process.".
> I know it is one of the FAQ issue, but I have no clue where is the form to enable this access for my user. (I tried to add a dummy totpSecret in my database for a given user, but it didn't work )

That route can only be called when you are within a 2fa process. That means you have to login first (usually with username+password), 2fa has to trigger (the requirements* for 2fa have to be fulfilled). Then, the bundle will automatically redirect to that route.

\* Requirements to trigger 2fa:
1) The `TwoFactorInterface` has to be implemented in the user entity, make sure you've not forgotten the correct `use` statements
2) `isTotpAuthenticationEnabled` has to return `true`
3) `getTotpAuthenticationConfiguration` has to return a configuration with a secret code

> Is there something already prepared like a ready-to-use layout/form ?

`/login/2fa` is showing a simple form asking for the 2fa code. You can overwrite the template or configure a different template name in the bundle config.

**Comment by meiyasan** [comment]
Thanks @scheb, I dealt myself adding the secret code to my database and created a controller for that. Looks good now.
It would be great to have some example interface like https://blog.silarhi.fr/symfony-double-authentification-2fa/, a demo is available here and working like a charm https://labs.silarhi.fr/

**Comment by scheb** [comment]
It's probably not that obvious, this respository contains a test application in the `app` folder that you can use to play around with the bundle.
