### ISSUE TITLE
TwoFactorPassport is not compatible with Symfony LoginSuccessEvent

### ISSUE THREAD

**Issue by jsawicki-internetcompany** [scheb/2fa#56]
I wanted to write a custom `LoginSuccessEventListener` that listens to `Symfony\Component\Security\Http\Event\LoginSuccessEvent`. This Symfony event has a `getUser(): UserInterface` method and it tries to get the User from the `$this->passport`. The passport has to implement `UserPassportInterface`. 

The `TwoFactorPassport` which is in: `vendor/scheb/2fa/src/bundle/Security/Http/Authenticator/Passport/TwoFactorPassport.php` does not implement the `UserPassportInterface` interface. `TwoFactorPassport` is implementing `PassportInterface` but not `UserPassportInterface`. 

The consequence of this is that the `TwoFactorPassport` is not compatible with the `LoginSuccessEvent`. 

My request: Can you implement the `UserPassportInterface` interface for the `TwoFactorPassport`?

**Comment by scheb** [comment]
I'm almost convinced. Before I implement anything, just to confirm:

@wouterj From your perspective, does it make sense to add `UserPassportInterface` to my custom `TwoFactorPassport`? There's definitely a user in that context, so I'd guess "yes"?

**Comment by wouterj** [comment]
Yes, definitely :)

This interface only exists because I want to play with idea of removing (or at least changing) `UserInterface`. But probably any normal passport should implement `UserPassportInterface`.

**Comment by scheb** [comment]
Thanks @wouterj, that was what I assumed. Good to know what's the intention behind it. Will add the interface as soon as I find some time.

@jsawicki-internetcompany PR also welcome if you like.

**Comment by scheb** [comment]
While trying to implement this, I realized `UserPassportInterface` requires an instance of `UserInterface` being returned. I cannot guarantee that, as the `TwoFactorToken` (or in general any security token) might return a string as well, so I'm likely going to throw a `RuntimeException` whenever I get something that isn't a `UserInterface`. Can't think of a better solution right now, I have to depend on what `TokenInterface` is returning and that's `UserInterface|string` unfortunately. "string" might also be legacy and not happening in a modern system, don't know.

@jsawicki-internetcompany Does that work for you?

**Comment by wouterj** [comment]
> "string" might also be legacy and not happening in a modern system, don't know.

Under normal usage, `string` indeed only occurs in the legacy system. It was used for: unauthenticated tokens (where `$user` holds the username from e.g. the input of the login form); or anonymous users (the famous `anon.`). Both cases are removed in the authenticator system (tokens are always authenticated and anonymous users are represented by the absence of a token).

**Comment by scheb** [comment]
@wouterj Good to know, then this is a case that's probably never going to happen, which let's me feel better about just throwing an exception there :)

**Comment by scheb** [comment]
Change released as v5.6.0.
