### ISSUE TITLE
Access URL /2FA with a logged in user without throwing a 403 error

### ISSUE THREAD

**Issue by sdespont** [scheb/2fa#63]
**Bundle version**: 5.4.2
**Symfony version**: 4.4.19
**PHP version**: 7.4.19
**Using authenticators** (`enable_authenticator_manager: true`): NO (becaise of 4.4 SF version)

**Description**
Some of my users have a favorite link in theirs browser, and they are using every day to reach my website pointing on http://mywesite/2fa

In case of the user is not logged in, the system will redirect him to the login webpage, perfect. But in case of the user is already logged in, he will hit a 403 error (forbidden) because of the security.yml rule :

        # This ensures that the form can only be accessed when two-factor authentication is in progress
        - { path: ^/(%app.locales%)/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS, requires_channel: "%requires_channel%" }

Is there a way to redirect to a specific route if the user is already logged in and try to reach the "2fa"URL?

**Additional Context**
None

**Comment by scheb** [comment]
I'd guess this should do the job: https://symfony.com/doc/current/security/access_denied_handler.html#customize-the-forbidden-response

You should get enough context from `$accessDeniedException` to decide that to do, whether to redirect or to show an error page.

**Comment by sdespont** [comment]
@scheb Thank you for your answer. I was thinking that this was handled by this library.
