### ISSUE TITLE
Support endroid/qr-code version 4

### ISSUE THREAD

**Issue by scheb** [scheb/2fa#65]
**Description**

Update `scheb/2fa-qr-code` to support `endroid/qr-code` version 4. If reasonable, keep compatibility with version 3 within the bundle's version 5.x.

**Comment by jamesisaac** [comment]
This would be nice.  v4 is needed for PHP8 support from what I see: https://github.com/endroid/qr-code/issues/306

**Comment by scheb** [comment]
Turns out the API of v4 is quite different, actually incompatible with the current interface of the `QrCodeGenerator`. So if we want to support both versions, we'd need to find some creative solution for it :/

**Comment by scheb** [comment]
I was playing through various solutions, in the end there's always a risk to break people's code. So I'll probably not do an upgrade until bundle version 6.

I'm considering to abandon the `scheb/2fa-qr-code` package as it's not really doing that much. It's really just [executing this one-liner](https://github.com/scheb/2fa/blob/5.x/src/qr-code/Security/TwoFactor/QrCode/QrCodeGenerator.php#L40) to create a `QrCode` object. All the rendering logic you have to implement yourself anyways.

*Workaround:*
To use `endroid/qr-code` version 4, I'd recommend you uninstall `scheb/2fa-qr-code` and use the `getQRContent` ([as shown here for Google Authenticator](https://github.com/scheb/2fa/blob/5.x/doc/providers/google.md#qr-codes) and [here for TOTP](https://github.com/scheb/2fa/blob/5.x/doc/providers/totp.md#qr-codes)) to fetch the QR code data. Then follow the [`endroid/qr-code` usage instructions](https://github.com/endroid/qr-code#usage-without-using-the-builder) to render a QR code from the data.

**Comment by Seldaek** [comment]
Complete all in one instructions for `endroid/qr-code:^4` without `scheb/2fa-qr-code` if it helps anyone:

```php
use Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticatorInterface;
use Endroid\QrCode\Builder\Builder;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelHigh;
use Endroid\QrCode\RoundBlockSizeMode\RoundBlockSizeModeMargin;
use Endroid\QrCode\Writer\PngWriter;

    public function renderQrCodeAction(TotpAuthenticatorInterface $totpAuthenticator): Response
    {
        $qrContent = $totpAuthenticator->getQRContent($this->getUser());

        $result = Builder::create()
            ->writer(new PngWriter())
            ->writerOptions([])
            ->data($qrContent)
            ->encoding(new Encoding('UTF-8'))
            ->errorCorrectionLevel(new ErrorCorrectionLevelHigh())
            ->size(300)
            ->margin(0)
            ->roundBlockSizeMode(new RoundBlockSizeModeMargin())
            ->build();

        return new Response($result->getString(), 200, ['Content-Type' => $result->getMimeType()]);
    }
```

Works wonders on PHP 8 :)

**Comment by scheb** [comment]
`scheb/2fa-qr-code` will be removed in bundle version 6, so please migrate to something like Seldaek's code example ☝️ to generate the QR code.
