### ISSUE TITLE
Ability to unset the trusted_device cookie on logout

### ISSUE THREAD

**Issue by Seldaek** [scheb/2fa#70]
I think this should even possibly be default behavior. If you lose your session due to inactivity that's one thing, but if you explicitly logout IMO the expectation is that the device is forgotten.

**Comment by scheb** [comment]
Under which circumstances would you want the trusted cookie to have an effect? If you have the remember-me cookie set and you lose the session, you'll be directly logged in again, 2fa doesn't trigger in that case.

**Comment by Seldaek** [comment]
The workflow is such:

- Login with remember-me enabled, which (on my setup, but how it is enabled is irrelevant) implicitly enables trusted_device
- Logout and expect I'll be completely forgotten
- Login again, I am not asked for 2fa code because trusted_device is still set

I hope that clarifies it.

Note that Symfony 5.1 added a LogoutEvent which may help here https://symfony.com/doc/current/security.html#customizing-logout

**Comment by scheb** [comment]
Oke, but then what would be the scenario when the trusted device cookie *would* have an effect? 🤔

**Comment by Seldaek** [comment]
If my session expires, and remember-me is still present to re-auth me, then trusted device should make it so that I do not need to enter 2fa again. This works fine, and I don't think it should change. I just think there's a difference between an user actively logging out, and a session becoming stale, which logs you out but can be recovered by remember-me cookie. 

Similarly, the remember-me cookie does not persist if the user actively logs out. I kind of expected the same for trusted device.

**Comment by scheb** [comment]
Did you manage to trigger 2fa when you're logged in with remember-me? Because to my understanding that shouldn't be possible. Could be in fact different with the new authenticator system.

**Comment by Seldaek** [comment]
Yes, if you have a page requiring IS_AUTHENTICATED_FULLY then it will ask for your password again, and if 2fa is enabled it then asks for 2fa again (unless trusted device is set).

**Comment by scheb** [comment]
Decided against making this an out-of-the-box feature. If someone needs that behaviour, you can now easily implement a `LogoutEvent` listener and clear the trusted cookie with the method provided in #71.
