### ISSUE TITLE
Ability to clear the trusted device cookie programmatically

### ISSUE THREAD

**Issue by Seldaek** [scheb/2fa#71]
Somewhat related to https://github.com/scheb/2fa/issues/70 - would it be possible to get a [TrustedDeviceTokenStorage](https://github.com/scheb/2fa/blob/5.x/src/trusted-device/Security/TwoFactor/Trusted/TrustedDeviceTokenStorage.php)::clearCookie or similar, that would trigger TrustedCookieResponseListener's to clearCookie on the response?

It's not that important, but my use case is: when disabling 2FA for a user, I would rather clear the trusted_device cookie to clean things up. I can do the clearCookie myself of course but then I need to replicate all the cookie config there vs reusing the bundle's config, so it would be slightly cleaner if I could trigger this at the bundle level. TrustedDeviceTokenStorage::clearTokens or other name might be more appropriate.

**Comment by scheb** [comment]
Added in 5.13.0. The `scheb_two_factor.trusted_token_storage` service now has a `clearTrustedToken` method.

**Comment by Seldaek** [comment]
Great, thanks!
