### ISSUE TITLE
Rendering the QR Code from string?

### ISSUE THREAD

**Issue by pixelcommerce** [scheb/2fa#77]
With the most recent version, how do you render the QR code into twig or just from the controller?

I'm passing the QR into the twig template like so:

```
return $this->render('account/enable2fa.html.twig', [
      "qr" => $qrCode->writeString(), 200, ['Content-Type' => 'image/png']
]);
```

The result on the twig template is this:
![image](https://user-images.githubusercontent.com/8448620/115787660-8e1fd100-a390-11eb-9ad3-1bd93529b95e.png)

So the question is, how do I render this effectively? Sorry for the noob quesiton, I'm new to this.

**Comment by scheb** [comment]
I don't really understand why you're passing the binary data of the PNG image to a template. You want to return an image, not a HTML page.

I believe this is what you really want:
```php
return new Response($qrCode->writeString(), 200, ['Content-Type' => 'image/png']);
```

**Comment by pixelcommerce** [comment]
I was hoping to have more control over where to place the QR code vs  displaying the image. Isn't that possible to do?

**Comment by scheb** [comment]
Then you have a route that responds with the QR-code image. Now you can put a `<img src="path to the route"/>` wherever you want.
