### ISSUE TITLE
Generate QR code to setup google 2FA

### ISSUE THREAD

**Issue by Segaja** [scheb/2fa#79]
Hi,

thanks for the great work in making this module.

I have 2FA with google working already and it works fine, but I have one question:

I want to generate a QR code to show to the user when he wants to add 2FA to his account. The problem is that either I can generate a secret to show to the user and add this secret to the db as his google secret, or I can show him a QR code, but than I don't know the secret and can't add it to his user entity.

What am I missing here?

Best regards
Segaja

**Comment by scheb** [comment]
You generate the secret, set the secret in the user enity and then generate a QR code as described in the documentation. You don't need to persist the user entity for generate the QR code.

**Comment by Segaja** [comment]
Thanks for the reply. So the workflow is:

- generate the code
- set it to the user entity
- generete QR code
- if the user activates 2FA => persist the entity
- if the user aborts => do nothing, as the secret will then be "lost" when the request is over

Is that correct?

**Comment by scheb** [comment]
Yes, like that.

I'd recommend to unset the secret if the user doesn't enable 2fa, because it might be that some other part of the system is persisting the user entity.

**Comment by Segaja** [comment]
Point taken. Thanks for clarifying this. I will close the issue. Should I have trouble I will re-open it. 

Thanks again for all the hard work.

**Comment by Segaja** [comment]
Hello @scheb , I have one more question:

According to https://github.com/scheb/2fa/blob/5.x/doc/providers/google.md#qr-codes I should build a new controller for the QR code and then include it as an image. But that would mean a new request from the client to the server. If I want to use the QR code as described earlier then how do I make sure this QR code is generated from the same secret, if I don't persist it to the DB yet?

**Comment by scheb** [comment]
Well, you have various options:

1) Actually persist the secret code and add a boolean field to switch `isGoogleAuthenticatorEnabled()` on, once the user has confirmed to enable 2fa.

2) Pass the QR code content as a query parameter to the controller and just render that content. But that would allow anyone to pass in arbitrary content to the controller, which would then be rendered as a QR code. So your controller becomes a QR code rendering service. You maybe don't want to do this except you add additional measure to prevent abuse.

3) Display the QR code as a [Data URI image](https://css-tricks.com/data-uris/), then you don't need another controller and pass data around. But then you'd need to properly encode (e.g. with base64) the binary data of the image that you get from the QR code generator.

**Comment by Segaja** [comment]
Thanks @scheb , option 3 works like a charm. a simple `\base64_encode()` was enough.

Thanks a lot for all the help.
