### ISSUE TITLE
Persist secret value in another entity/table

### ISSUE THREAD

**Issue by blackarcanis** [scheb/2fa#84]
Hi!
Quick question: To save the secret value, we need to have "googleAuthenticatorSecret" (or another name) but persisted into the "User" entity (and so, in my user table in the database too). 

How can I do to have this secret value in another table (for example, a "user settings" table)? Don't want to have this user entity/table with too many columns. 
A suggestion? Probably more a Symfony question than a bundle question here but I need some advice.

Thank you!

**Comment by scheb** [comment]
You don't need to implement that property in the user entity, you "just" need to have the getter method `getGoogleAuthenticatorSecret` implemented.

Doctrine lets you to read from related tables via the [One-To-One relations](https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/association-mapping.html#one-to-one-unidirectional). You can use this feature to read the secret from a related table/entity and return if through the `getGoogleAuthenticatorSecret()` method.

**Comment by blackarcanis** [comment]
OK I see, great :)
Thank you for your prompt response!
