### ISSUE TITLE
Notify user when all backup codes are used

### ISSUE THREAD

**Issue by blackarcanis** [scheb/2fa#91]
Hi!
I'm curious about what should I do when the user has used all its backup codes.
Should I send an email to him when I invalidate the last backup code? Or before? How to set up a listener on that?

Or maybe there's another solution or another "good practice" about this backup code list?

Thank you!

**Comment by scheb** [comment]
I don't really know how people are usually doing it. It should be rather obvious to the user when their backup code list is about to end, as they'd store this list somewhere and typically cross-out/remove used codes from the list.

If you want some notification solution, you could build your own [backup code manager](https://github.com/scheb/2fa/blob/5.x/doc/backup_codes.md#custom-backup-code-manager) that checks how many codes are still available after a code being used, and then you tigger the notification from there.

**Comment by blackarcanis** [comment]
Yes, by reading you, it seems more logical now... However, I'm taking note of this, it will be quite easy to do the notification process by building my own backup code manager if I need it (I was missing this part).

All good for me, thank you!
