### ISSUE TITLE
Custom two-factor authenticator getFormRenderer

### ISSUE THREAD

**Issue by ghost** [scheb/2fa#92]
Hello,

Is it possible to provide the correct way to implement the getFormRenderer (custom authenticator) when using: 
- a custom template page twofactor.html.twig 
- with associated array parameters for the page array(
                                                         'method'      => $twoFactorLatestMethod,
                                                         'phoneNumber' => $phoneNumber,
                                                         'email'       => $email
                                                     )
and returning a TwoFactorFormRendererInterface return type

a code example would be welcome

thank you for your help

**Comment by scheb** [comment]
Create a custom form renderer:
```php
class CustomFormRenderer implements TwoFactorFormRendererInterface
{
    private $twigEnvironment;

    public function __construct(Environment $twigRenderer) {
        $this->twigEnvironment = $twigRenderer;
    }

    public function renderForm(Request $request, array $templateVars): Response
    {
        // Add the extra template variables
        // I don't know where these variables are coming from, you likely need to inject extra dependencies
        $templateVars = array_merge($templateVars[
            'method' => $twoFactorLatestMethod,
            'phoneNumber' => $phoneNumber,
            'email' => $email
        ];

        $content = $this->twigEnvironment->render($template, $templateVars);
        $response = new Response();
        $response->setContent($content);

        return $response;
    }
}
```

Configure it as a service:

```yaml
# config/services.yaml
services:
    custom_form_renderer:
        class: CustomFormRenderer
        arguments:
            - '@twig'
```

In your two-factor provider, inject that service and return it via the `getFormRenderer()` method:

```php
class MyCustomTwoFactorProvider implements TwoFactorProviderInterface
{
    /**
     * @var TwoFactorFormRendererInterface
     */
    private $formRenderer;

    public function __construct(TwoFactorFormRendererInterface $formRenderer)
    {
        $this->formRenderer = $formRenderer;
    }

    // ...

    public function getFormRenderer(): TwoFactorFormRendererInterface
    {
        return $this->formRenderer;
    }
}
```

**Comment by ghost** [comment]
Great thank you for the explanation, work perfectly
