### ISSUE TITLE
Set an expiration time to pass the /2fa step

### ISSUE THREAD

**Issue by blackarcanis** [scheb/2fa#96]
Hi!
Quick question: when the user successfully passes the first step login (like username/password), he is redirected to /2fa. 
But then, if he's not filling this second step, the user is stuck on this interface, as long is not going to a /logout. 

Is it possible to set an expiration time (like 5min) on "TwoFactorToken" token class? Because currently, the user will get this interface as long the session cookie is valid (could be multiple days...). 
That should be great to be able to invalidate this two factor stage if the user is not processing it in X minutes. And so, he will get back to the main page/login page or whatever.

Not sure if I'm clear, so let me know.
Thank you !

**Comment by scheb** [comment]
You could set an attribute on the `TwoFactorToken` with the current time, subscribe to the login event to do that. Then, on every request check how much time has passed and if needed force a logout.

**Comment by MarkCenturion** [comment]
What I did in this situation as well was I implemented a Javascript timeout on the form itself.

If a user logins in then gets distracted, it sits on this form. If he then comes back later and submits a 2FA code, if the session is timed out and been cleared he will be sent back to the main login with no "warning", which can result in support "my 2fa is not working" complaints.

A JS timeout on the form itself allows me to call /logout directly after a short period of inactivity and flush the session (so its not hanging half authenticated) as well as show the user a count down timer to session expiry, given a visual indication of urgency.

The JS timer works well for this as the session will hang until a new request is made if you have only a server-side timeout as typically not requests are being made during the time this form is being shown
