### ISSUE TITLE
Invalidating other sessions

### ISSUE THREAD

**Issue by norkunas** [scheb/2fa#99]
**Description**

Would be nice to have an option to invalidate user sessions on other devices but leave the one who enabled two factor auth.

**Comment by scheb** [comment]
In my opinion that should be something Symfony's security component should be handling. Maybe there are already solutions to this problem that I'm not aware of. If there are, you could easily subscribe to 2fa events and execute invalidation for other sessions when 2fa is completed.

Overall, this is not a concern for 2fa, I'd suggest you bring that up as a feature request for the Symfony security component.
